### ISSUE TITLE
Problems about VIPL data set...

### ISSUE THREAD

**Issue by CrossguoAND** [ubicomplab/rPPG-Toolbox#102]
Dear author,

Hi! Thanks for your contribution, and I have made good results on PURE, UBFC, and CONHFACE because of this toolbox. Recently I tried to train on the VIPL data set. Here is what I did:
1)  VIPL data set contains two files: video.avi and wave.csv. So I changed def read_wave(bvp_file) function to read CSV file.
![image](https://user-images.githubusercontent.com/76768087/197924233-50e68f15-9b3a-4050-b4a0-54dac1460f30.png)
![image](https://user-images.githubusercontent.com/76768087/197924402-4e765d62-dc71-48d6-bfb8-0233fb79954a.png)
2) The video format in CONHFACE is also avi, so I didn't change the function of the read video:
![image](https://user-images.githubusercontent.com/76768087/197924621-47f318ef-42cc-4d8f-8499-04c1f77975e6.png)
3) The length of the wave doesn't match the length of the video in VIPL, so following your code, I did the sample too:
![image](https://user-images.githubusercontent.com/76768087/197924840-50468857-efed-4251-895b-dc0f43dede7c.png)

Apart from these, I did not make any other modifications. I used TSCAN to train, but I couldn't get good results. Here are the predicted PPG signal and ground-truth signal:
![image](https://user-images.githubusercontent.com/76768087/197925082-b8ed8d31-fc30-45a0-8fed-8702d296ed2c.png)
![image](https://user-images.githubusercontent.com/76768087/197925097-fd9070c3-bd16-4d85-bd78-fbe74514a2a7.png)
In the predicted PPG signal, it can be seen that the model predicts the periodicity, but the frequency is wrong.

The MAE is over 30, sorry I didn't have a screenshot of the last results. 

Do you have any clues about this problem?

**Comment by 1625298892** [comment]
It's not TS-CAN's fault, I have a good reproduction of this model.
When I first entered this field, my work was first carried out on VIPL-HR, I spent a lot of time on it, tried RhythmNet, PhysNet, TS-CAN, and our own method, but could not get high accuracy , the MAE is always around 10.
It should be noted that the frame rate of VIPL-HR is not fixed, some videos have 30fps, and some have only 17, 18.
In general, it always seems difficult to work on VIPL-HR, although these methods test well on other datasets.

**Comment by CrossguoAND** [comment]
Thanks for your reply! Last week I changed VIPL-HR and only kept the videos whose fps is 25. So I could make sure the fps are stable. But the results were still wrong. I guess the problem with VIPL-HR is the compression method, and I noticed the raw videos of VIPL-HR have some noise. PURE and UBFC are both uncompressed videos, so I guess the reason is related to the compression.

**Comment by 1625298892** [comment]
Yes. The videos of VIPL-HR has obvious noise, but this is not the problem of the compression format, its format is MJPG, the same as UBFC-Phys, but the above algorithms can work well on UBFC-Phys. I think the issue with VIPL-HR needs further confirmation.

**Comment by CrossguoAND** [comment]
Sorry, I forgot the compression format of UBFC-Phys data set so I made a mistake. And if you find out what's the actual problems of VIPL pls tell me. If I find out, I will comment on this issue too. Thanks for your help!

**Comment by 1625298892** [comment]
> The released version of VIPL-HR is compressed based on the collected version (also compressed based on different recording devices). About one year ago this was mentioned on VIPL-HR' website but now can't find website anymore. May I know if the size of your VIPL-HR dataset is around 40GB? Also, I found another two issues about the VIPL-HR dataset. One is that some ground-truth PPGs are pretty noisy and there is no official analysis/description/suggestion about how to deal with it. Shall we remove the entire sample or just the noisy slots? Another one is that the head rotation in some videos is quite severe (100% side face), or the head is out of view. Don't know how the STMAP (defined in their papers) is constructed in these cases and this is not mentioned in their paper as well.


There is an example in the code that comes with CVD (ECCV 2020) where they read facial landmarks from a file and then segment the frame. It's disappointing that they didn't share the full landmark file, and we still can't pin down the details of the facial segmentation.

https://github.com/nxsEdson/CVD-Physiological-Measurement

I don't think it's difficult to generate STMaps, the RhythmNet paper describes it in detail, and this method can be used for other datasets. But I still can't reproduce it on VIPL-HR  

I got the dataset from the link shared by Hu Han, the size is 47.8 GB, it should be the same version

**Comment by Scratch5566** [comment]
> > The released version of VIPL-HR is compressed based on the collected version (also compressed based on different recording devices). About one year ago this was mentioned on VIPL-HR' website but now can't find website anymore. May I know if the size of your VIPL-HR dataset is around 40GB? Also, I found another two issues about the VIPL-HR dataset. One is that some ground-truth PPGs are pretty noisy and there is no official analysis/description/suggestion about how to deal with it. Shall we remove the entire sample or just the noisy slots? Another one is that the head rotation in some videos is quite severe (100% side face), or the head is out of view. Don't know how the STMAP (defined in their papers) is constructed in these cases and this is not mentioned in their paper as well.
> 
> There is an example in the code that comes with CVD (ECCV 2020) where they read facial landmarks from a file and then segment the frame. It's disappointing that they didn't share the full landmark file, and we still can't pin down the details of the facial segmentation.
> 
> https://github.com/nxsEdson/CVD-Physiological-Measurement
> 
> I don't think it's difficult to generate STMaps, the RhythmNet paper describes it in detail, and this method can be used for other datasets. But I still can't reproduce it on VIPL-HR
> 
> I got the dataset from the link shared by Hu Han, the size is 47.8 GB, it should be the same version

I also generate the STMaps using code from this repo. Given the facial landmarks, we can get multiple ROIs using roipoly() in matlab and then calculate the STMap.
But when the head is out of view there is no way to generate ROIs as the landmarks are not available. Also for 100% side face cases, half of the ROIs are not available. Not sure how they handles these cases.

Also, if you visualize all ground truth PPG signals, you will find a lot of them are noisy. Don't know how to train or evaluate using these samples. Maybe they remove those noisy slots/frames but details are not available in their paper or anywhere else.

**Comment by 1625298892** [comment]
> > > The released version of VIPL-HR is compressed based on the collected version (also compressed based on different recording devices). About one year ago this was mentioned on VIPL-HR' website but now can't find website anymore. May I know if the size of your VIPL-HR dataset is around 40GB? Also, I found another two issues about the VIPL-HR dataset. One is that some ground-truth PPGs are pretty noisy and there is no official analysis/description/suggestion about how to deal with it. Shall we remove the entire sample or just the noisy slots? Another one is that the head rotation in some videos is quite severe (100% side face), or the head is out of view. Don't know how the STMAP (defined in their papers) is constructed in these cases and this is not mentioned in their paper as well.
> > 
> > 
> > There is an example in the code that comes with CVD (ECCV 2020) where they read facial landmarks from a file and then segment the frame. It's disappointing that they didn't share the full landmark file, and we still can't pin down the details of the facial segmentation.
> > https://github.com/nxsEdson/CVD-Physiological-Measurement
> > I don't think it's difficult to generate STMaps, the RhythmNet paper describes it in detail, and this method can be used for other datasets. But I still can't reproduce it on VIPL-HR
> > I got the dataset from the link shared by Hu Han, the size is 47.8 GB, it should be the same version
> 
> I also generate the STMaps using code from this repo. Given the facial landmarks, we can get multiple ROIs using roipoly() in matlab and then calculate the STMap. But when the head is out of view there is no way to generate ROIs as the landmarks are not available. Also for 100% side face cases, half of the ROIs are not available. Not sure how they handles these cases.
> 
> Also, if you visualize all ground truth PPG signals, you will find a lot of them are noisy. Don't know how to train or evaluate using these samples. Maybe they remove those noisy slots/frames but details are not available in their paper or anywhere else.

I'm guessing it's possible to delete these images that don't contain a full face. Unlike TS-CAN, RhythmNet does not output BVP waveform, but directly gives heart rate, so you can use heart rate data directly(in gt_HR.csv)

**Comment by Scratch5566** [comment]
> 

Thanks for the suggestion. I am working on some 3D-convolution-based networks which output the rPPG signal. The HR is obtained by analyzing the spectrum. Without knowing the exact frames/slots that are removed, it is hard to have a fair comparison with those baselines that have been tested on VIPL-HR dataset.

**Comment by Scratch5566** [comment]
> > > > The released version of VIPL-HR is compressed based on the collected version (also compressed based on different recording devices). About one year ago this was mentioned on VIPL-HR' website but now can't find website anymore. May I know if the size of your VIPL-HR dataset is around 40GB? Also, I found another two issues about the VIPL-HR dataset. One is that some ground-truth PPGs are pretty noisy and there is no official analysis/description/suggestion about how to deal with it. Shall we remove the entire sample or just the noisy slots? Another one is that the head rotation in some videos is quite severe (100% side face), or the head is out of view. Don't know how the STMAP (defined in their papers) is constructed in these cases and this is not mentioned in their paper as well.
> > > 
> > > 
> > > There is an example in the code that comes with CVD (ECCV 2020) where they read facial landmarks from a file and then segment the frame. It's disappointing that they didn't share the full landmark file, and we still can't pin down the details of the facial segmentation.
> > > https://github.com/nxsEdson/CVD-Physiological-Measurement
> > > I don't think it's difficult to generate STMaps, the RhythmNet paper describes it in detail, and this method can be used for other datasets. But I still can't reproduce it on VIPL-HR
> > > I got the dataset from the link shared by Hu Han, the size is 47.8 GB, it should be the same version
> > 
> > 
> > I also generate the STMaps using code from this repo. Given the facial landmarks, we can get multiple ROIs using roipoly() in matlab and then calculate the STMap. But when the head is out of view there is no way to generate ROIs as the landmarks are not available. Also for 100% side face cases, half of the ROIs are not available. Not sure how they handles these cases.
> > Also, if you visualize all ground truth PPG signals, you will find a lot of them are noisy. Don't know how to train or evaluate using these samples. Maybe they remove those noisy slots/frames but details are not available in their paper or anywhere else.
> 
> I'm guessing it's possible to delete these images that don't contain a full face. Unlike TS-CAN, RhythmNet does not output BVP waveform, but directly gives heart rate, so you can use heart rate data directly(in gt_HR.csv)

Thanks for the suggestion. I am working on some 3D-convolution-based networks which output the rPPG signal. The HR is obtained by analyzing the spectrum. Without knowing the exact frames/slots that are removed, it is hard to have a fair comparison with those baselines that have been tested on VIPL-HR dataset.
