### ISSUE TITLE
Are there any pre-trained models that can be used for inference?

### ISSUE THREAD

**Issue by matt-sharp** [ubicomplab/rPPG-Toolbox#118]
I don't see any links to pre-trained models, are these available for any of the methods?

**Comment by yahskapar** [comment]
I believe pre-trained models for all publicly supported datasets will be released soon ([as discussed in another issue](https://github.com/ubicomplab/rPPG-Toolbox/issues/91#issuecomment-1289264646)) along with an update to the README of this repo. Keep an eye out. At that point, you should be able to use the models for inference while configuring the toolbox in "only_test" mode.

**Comment by xliucs** [comment]
Hi Sorry, we have been doing large reformating and update to the toolbox. You can use the pre-trianed models now. Pleasse refer to the latest readme.

**Comment by xliucs** [comment]
@matt-sharp

**Comment by matt-sharp** [comment]
Thanks for the update @xliucs 
Is it possible to run inference on our own data using the pre-trained models?
