### ISSUE TITLE
Two functions not found in 'signal_predictor.py'

### ISSUE THREAD

**Issue by ChainShoeTall** [ubicomplab/rPPG-Toolbox#119]
calculate_metric_peak_per_video in line 49
calculate_metric_per_video in line 54

**Comment by yahskapar** [comment]
Hi, good catch - this will be fixed in this PR that's already up: https://github.com/ubicomplab/rPPG-Toolbox/pull/116#issue-1550344568.

I'll post back here when that happens and then close this issue.

**Comment by ChainShoeTall** [comment]
Thanks for your kind reply

**Comment by ChainShoeTall** [comment]
It seems like the "calculate_metric_peak_per_video" function was merged with "calculate_metric_per_video" with additional parameters hr_method but not updated in this script

**Comment by xliucs** [comment]
@ChainShoeTall  We will fix this issue asap.

**Comment by yahskapar** [comment]
This is now fixed in 34f3cb1e134013321801a03d9feaf6e2a0aa2026. I'll go ahead and close this issue. Please feel free to open another issue if somehow the problem persists on your end with the latest changes, or if you notice another problem pop up. Thanks!
