### ISSUE TITLE
Real time rPPG extraction through camera feed. 

### ISSUE THREAD

**Issue by Bala93** [ubicomplab/rPPG-Toolbox#135]
Thanks for this repository. Are you planning to add rPPG extraction from real-time camera stream anytime soon ?

**Comment by Bala93** [comment]
Thanks for your prompt response. I am working on extracting the rPPG waveform from a video, once I complete, may be I can create a pull request. If it fits with your repository, you could consider it.

**Comment by yahskapar** [comment]
Would this be a real-time demo that could leverage models trained by this repo? If so, I think that would be reasonable to include in this repo eventually - we and the rest of the community would appreciate that contribution! If it's a real-time demo that doesn't leverage other aspects of this repo (e.g., the models), then I'd recommend making a separate repo.

Also, if you don't mind and if don't have any other questions on this topic, I'll go ahead and close this issue. Again, thank you again for being willing to contribute what you are working on!

**Comment by Bala93** [comment]
Thankyou. I will close the issue.
