### ISSUE TITLE
Real time rPPG extraction through camera feed.

### ISSUE THREAD

**Issue by Ghulam-Nabii** [ubicomplab/rPPG-Toolbox#137]
is there any real-time deep learning repo that measures heart rate pulse?

**Comment by girishvn** [comment]
Hi @Ghulam-Nabii currently this repo does not support real-time pulse measurement (though some models implemented in the neural methods have been shown to work in real/near-real time). 

I personally was unable to find other git repos that implement rPPG in real-time, but you would essentially need to train a model (which you could do through this toolbox), and then write infrastructure to capture / prepreocess frames and pass them through a model in chunks of reasonable length for real-time applications. 

Hope this helps
