### ISSUE TITLE
How to download the UBFC-rPPG Dataset?

### ISSUE THREAD

**Issue by KenTee920806** [ubicomplab/rPPG-Toolbox#140]
May I know how to download the UBFC-rPPG dataset from this [link](https://sites.google.com/view/ybenezeth/ubfcrppg)?
I have try to contact with the authors for requesting the dataset, but I didn't get the reply.

**Comment by GaoXu007** [comment]
hi @KenTee920806 That's right, to obtain the UBFC dataset, you need to contact the author via email. How long ago did you send the email? It might take a few days for them to reply. Alternatively, you can try contacting another author to see if they can help.

**Comment by KenTee920806** [comment]
Hi @GaoXu007 thanks for your reply. I emailed to them yesterday, maybe I should wait for a few more days.
