### ISSUE TITLE
About the blood pressure

### ISSUE THREAD

**Issue by ZechenZed** [ubicomplab/rPPG-Toolbox#146]
Hi guys, 

You guys have done great work in predicting HR and RR. I am working on using the rPPG signal predicted to blood pressure. Do you have some recommendations regarding this?

**Comment by yahskapar** [comment]
Hi @ZechenZed,

I personally have not directly worked with blood pressure from PPG before, and perhaps @xliucs or @girishvn could shed some personal experience if they have worked with blood pressure from PPG before, but I recommend reading [the blood pressure section on page 11 of this excellent review article](https://dl.acm.org/doi/pdf/10.1145/3558518) and this [recent article](https://arxiv.org/pdf/2304.14916.pdf) regarding blood pressure from PPG signal. The latter article actually further suggests that blood pressure from PPG is unsolved and nowhere near certain standards, but may provide some useful insights and [code](https://github.com/lirus7/PPG-BP-Analysis) to guide you in your research.

All the best!

**Comment by ZechenZed** [comment]
Hi @yahskapar，

Thanks a lot for your quick response and great resources to look at. I will share something useful too regarding the blood pressure here with you guys if I find some useful information. 

Best Regards!

**Comment by girishvn** [comment]
Hi @ZechenZed,

Like @yahskapar mentioned, the blood pressure from PPG is still a very much unsolved research question. Most works to date require some amount of calibration to calculate BP from PPG. Here is a some work from Rama Mukkamala's group at the University of Pittsburg which I think is interesting (their group also has a number of review papers):
https://www.engineering.pitt.edu/subsites/Labs/chtl/research/

**Comment by ZechenZed** [comment]
Hi @girishvn,

Thanks for the information. Yes, I strongly agree with your part regarding the calibration. And, it is good to know the University of Pittsburgh is researching in the same direction so I may have a chance to talk with them in person. 

Best Regards!

**Comment by girishvn** [comment]
Yes, definitely keep us posted if you see any other interesting BP work or have some interesting finding! 
I'm going to close this thread for the time being, but feel free to open if need. 

Thanks!
