### ISSUE TITLE
RuntimeError in TS_CAN.py

### ISSUE THREAD

**Issue by Changezi001** [ubicomplab/rPPG-Toolbox#157]
Hi,

I want to use the pretrained TSCAN model to get the rppg data from my own videos, and the shape of my input to the model is [300, 3, 128, 128]. But, I am getting a runtime error given below:

RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[300, 0, 128, 128] to have 3 channels, but got 0 channels instead

The error is occurring at /neural_methods/model/TS_CAN.py", line 127, in forward
    r1 = torch.tanh(self.apperance_conv1(raw_input))

Because in line 120 in TS_CAN.py, where we get the raw_data, i.e., raw_input = inputs[:, 3:, :, :], it is getting raw_input which is of shape [300, 0, 128, 128]. Could you tell me what is the expected shape of raw_input here?

My code is given below:

import torch
from neural_methods.model.TS_CAN import TSCAN
from config import get_config
import cv2
import numpy as np
from math import ceil

def read_video(video_file):
    """Reads a video file, returns frames(T, H, W, 3) """
    VidObj = cv2.VideoCapture(video_file)
    VidObj.set(cv2.CAP_PROP_POS_MSEC, 0)
    success, frame = VidObj.read()
    frames = list()
    while success:
        frame = cv2.cvtColor(np.array(frame), cv2.COLOR_BGR2RGB)
        frame = np.asarray(frame)
        frames.append(frame)
        success, frame = VidObj.read()
    return np.asarray(frames)

def preprocess(frames, config_preprocess):

    frames = crop_face_resize(frames,
        True,
        True,
        1.5,
        False,
        30,
        False,
        128,
        128)

    # Check data transformation type
    data = list()  # Video data
    f_c = frames.copy()
    data.append(f_c)
    data = np.concatenate(data, axis=-1)  # concatenate all channels
    frames_clips = np.array([data])

    return frames_clips

def crop_face_resize(frames, use_face_detection, use_larger_box, larger_box_coef, use_dynamic_detection,
                     detection_freq, use_median_box, width, height):
    # Face Cropping
    if use_dynamic_detection:
        num_dynamic_det = ceil(frames.shape[0] / detection_freq)
    else:
        num_dynamic_det = 1
    face_region_all = []
    # Perform face detection by num_dynamic_det" times.
    for idx in range(num_dynamic_det):
        if use_face_detection:
            face_region_all.append(face_detection(frames[detection_freq * idx], use_larger_box, larger_box_coef))
        else:
            face_region_all.append([0, 0, frames.shape[1], frames.shape[2]])
    face_region_all = np.asarray(face_region_all, dtype='int')
    if use_median_box:
        # Generate a median bounding box based on all detected face regions
        face_region_median = np.median(face_region_all, axis=0).astype('int')

    # Frame Resizing
    resized_frames = np.zeros((frames.shape[0], height, width, 3))
    for i in range(0, frames.shape[0]):
        frame = frames[i]
        if use_dynamic_detection:  # use the (i // detection_freq)-th facial region.
            reference_index = i // detection_freq
        else:  # use the first region obtrained from the first frame.
            reference_index = 0
        if use_face_detection:
            if use_median_box:
                face_region = face_region_median
            else:
                face_region = face_region_all[reference_index]
            frame = frame[max(face_region[1], 0):min(face_region[1] + face_region[3], frame.shape[0]),
                    max(face_region[0], 0):min(face_region[0] + face_region[2], frame.shape[1])]
        resized_frames[i] = cv2.resize(frame, (width, height), interpolation=cv2.INTER_AREA)
    return resized_frames

def face_detection(frame, use_larger_box=False, larger_box_coef=1.0):

    detector = cv2.CascadeClassifier('./dataset/haarcascade_frontalface_default.xml')
    face_zone = detector.detectMultiScale(frame)
    if len(face_zone) < 1:
        print("ERROR: No Face Detected")
        face_box_coor = [0, 0, frame.shape[0], frame.shape[1]]
    elif len(face_zone) >= 2:
        face_box_coor = np.argmax(face_zone, axis=0)
        face_box_coor = face_zone[face_box_coor[2]]
        print("Warning: More than one faces are detected(Only cropping the biggest one.)")
    else:
        face_box_coor = face_zone[0]
    if use_larger_box:
        face_box_coor[0] = max(0, face_box_coor[0] - (larger_box_coef - 1.0) / 2 * face_box_coor[2])
        face_box_coor[1] = max(0, face_box_coor[1] - (larger_box_coef - 1.0) / 2 * face_box_coor[3])
        face_box_coor[2] = larger_box_coef * face_box_coor[2]
        face_box_coor[3] = larger_box_coef * face_box_coor[3]
    return face_box_coor

def predict_vitals():

    # configurations.
    config = get_config()
    print('Configuration:')
    print(config, end='\n\n')
    config = config
    frame_depth = 10

    kam_device = torch.device("cuda")  # Use CUDA device
    TSCAN_model = TSCAN(frame_depth=frame_depth, img_size=72).to(kam_device)

    # Load the saved state_dict
    state_dict = torch.load('final_model_release/UBFC_TSCAN.pth')
    # Create a new state_dict with modified keys
    new_state_dict = {}
    for key, value in state_dict.items():
        if key.startswith('module.'):
            new_key = key[len('module.'):]
        else:
            new_key = key
        new_state_dict[new_key] = value

    # Use the new_state_dict in your model
    TSCAN_model.load_state_dict(new_state_dict)
    TSCAN_model.eval()
    vid_path = 'my_vid.mp4'
    frames = read_video(vid_path)
    frames_clips = preprocess(frames, config.TEST.DATA)
    frames_clips = np.squeeze(frames_clips, axis=0)
    frames_clips_transposed = np.transpose(frames_clips, (0, 3, 1, 2))
    data = np.float32(frames_clips_transposed)
    data_tnsr = torch.from_numpy(data)
    data_tnsr = data_tnsr.to(kam_device)
    num_of_gpu = 1
    frame_depth = 10
    base_len = num_of_gpu * frame_depth
    ND, C, H, W = data_tnsr.shape
    data_tnsr = data_tnsr.view(ND, C, H, W)
    data_test = data_tnsr[:(ND) // base_len * base_len]
    #print('data_test shape:', data_test.shape)

    with torch.no_grad():
        pred_ppg_test = TSCAN_model(data_test)
        print('pred_ppg_test:', pred_ppg_test)

if __name__ == "__main__":
    predict_vitals()

**Comment by girishvn** [comment]
Hi @Changezi001 does this occur during training, or test (or both)? How many GPUs are you using (if any)?

The TSCAN model reshapes the input batches in order to follow protocol used by the original TSCAN publication.
Can you print out the batch size when it originally fetched and then once again after the batch is reshaped?

**Comment by yahskapar** [comment]
Hi @Changezi001,

Few things in addition to what @girishvn already mentioned (and are still important to note):

1. This is because instead of having an input that consists of normalized difference frames and standardized raw RGB frames, you're passing in what appears to be just raw RGB frames. You need to make sure your data is preprocessed as TS-CAN would expect it to be (and as is normally done in the toolbox). That means your input to the model should really be [300, 6, 128, 128]. 

If you want to stick to your current approach of working with fragments of the toolbox rather than in the toolbox directly, I recommend changing your customized preprocess function to as follows:

```
def preprocess(frames, config_preprocess):
  frames = crop_face_resize(frames,
      True,
      True,
      1.5,
      False,
      30,
      False,
      128,
      128)
  
  # Check data transformation type
  data = list()  # Video data
  f_c = frames.copy()
  data.append(BaseLoader.diff_normalize_data(f_c)) # Get normalized difference frames
  data.append(BaseLoader.standardized_data(f_c)) # Get standardized RGB frames
  data = np.concatenate(data, axis=-1)  # concatenate all channels
  frames_clips = np.array([data])
  
  return frames_clips
```

You can re-use the functions from [here](https://github.com/yahskapar/rPPG-Toolbox/blob/main/dataset/data_loader/BaseLoader.py#L541) and [here](https://github.com/yahskapar/rPPG-Toolbox/blob/main/dataset/data_loader/BaseLoader.py#L565) in your files.

2. If you are intending to just test a pre-trained TS-CAN model on your custom rPPG videos, why not just create a very simple data loader based on the existing data loaders to load the one video you care about, create a new config similar to the ones in `configs/infer_configs`, create a very simple data loader based on the existing data loaders, save the prediction as a `.npy` file or plot it out [after this line of code](https://github.com/yahskapar/rPPG-Toolbox/blob/main/evaluation/post_process.py#L111), and then re-use the remainder of the toolbox code directly? There is a good chance your current approach will introduce bugs into your code, especially if you plan on re-using the arrangement of code in your current approach outside of the toolbox for other experiments.

**Comment by Changezi001** [comment]
Hi @girishvn and @yahskapar 

Thank you for the prompt response. I am just testing a single video, and I am interested in getting the rppg signal. I am using the TSCAN model. I, as suggested by @yahskapar , have resolved my previous issue by using the diff_normalize_data() and standardized_data() functions, but unfortunately, I am now getting a constant rppg signal with zero frequency, i.e., I am getting a tensor of shape [300, 1] for an input of shape [300, 6, 72, 72], where all the 300 entries have the same value, which is undesired. I used all three pre-trained TSCAN weights, and I noticed the same weird phenomena in all three cases. Could you shed some light on what could be wrong?

My code is given below:

import torch
from neural_methods.model.TS_CAN import TSCAN
from config import get_config
import cv2
import numpy as np
from math import ceil
#from dataset.data_loader.BaseLoader import BaseLoader

def diff_normalize_data(data):
    n, h, w, c = data.shape
    diffnormalized_len = n - 1
    diffnormalized_data = np.zeros((diffnormalized_len, h, w, c), dtype=np.float32)
    diffnormalized_data_padding = np.zeros((1, h, w, c), dtype=np.float32)
    for j in range(diffnormalized_len - 1):
        diffnormalized_data[j, :, :, :] = (data[j + 1, :, :, :] - data[j, :, :, :]) / (
                data[j + 1, :, :, :] + data[j, :, :, :] + 1e-7)
    diffnormalized_data = diffnormalized_data / np.std(diffnormalized_data)
    diffnormalized_data = np.append(diffnormalized_data, diffnormalized_data_padding, axis=0)
    diffnormalized_data[np.isnan(diffnormalized_data)] = 0
    return diffnormalized_data

def standardized_data(data):
    data = data - np.mean(data)
    data = data / np.std(data)
    data[np.isnan(data)] = 0
    return data

def read_video(video_file):
    """Reads a video file, returns frames(T, H, W, 3) """
    VidObj = cv2.VideoCapture(video_file)
    VidObj.set(cv2.CAP_PROP_POS_MSEC, 0)
    success, frame = VidObj.read()
    frames = list()
    while success:
        frame = cv2.cvtColor(np.array(frame), cv2.COLOR_BGR2RGB)
        frame = np.asarray(frame)
        frames.append(frame)
        success, frame = VidObj.read()
    return np.asarray(frames)

def preprocess(frames):

    frames = crop_face_resize(frames,True,True,1.5,False,30,False,72,72)
    # Check data transformation type
    data = list()  # Video data
    f_c = frames.copy()
    data.append(diff_normalize_data(f_c)) # Get normalized difference frames
    data.append(standardized_data(f_c)) # Get standardized RGB frames
    data = np.concatenate(data, axis=-1)  # concatenate all channels
    frames_clips = np.array([data])

    return frames_clips

def crop_face_resize(frames, use_face_detection, use_larger_box, larger_box_coef, use_dynamic_detection,
                     detection_freq, use_median_box, width, height):

    if use_dynamic_detection:
        num_dynamic_det = ceil(frames.shape[0] / detection_freq)
    else:
        num_dynamic_det = 1
    face_region_all = []
    # Perform face detection by num_dynamic_det" times.
    for idx in range(num_dynamic_det):
        if use_face_detection:
            face_region_all.append(face_detection(frames[detection_freq * idx], use_larger_box, larger_box_coef))
        else:
            face_region_all.append([0, 0, frames.shape[1], frames.shape[2]])
    face_region_all = np.asarray(face_region_all, dtype='int')
    if use_median_box:
        # Generate a median bounding box based on all detected face regions
        face_region_median = np.median(face_region_all, axis=0).astype('int')

    # Frame Resizing
    resized_frames = np.zeros((frames.shape[0], height, width, 3))
    for i in range(0, frames.shape[0]):
        frame = frames[i]
        if use_dynamic_detection:  # use the (i // detection_freq)-th facial region.
            reference_index = i // detection_freq
        else:  # use the first region obtrained from the first frame.
            reference_index = 0
        if use_face_detection:
            if use_median_box:
                face_region = face_region_median
            else:
                face_region = face_region_all[reference_index]
            frame = frame[max(face_region[1], 0):min(face_region[1] + face_region[3], frame.shape[0]),
                    max(face_region[0], 0):min(face_region[0] + face_region[2], frame.shape[1])]
        resized_frames[i] = cv2.resize(frame, (width, height), interpolation=cv2.INTER_AREA)
    return resized_frames

def face_detection(frame, use_larger_box=False, larger_box_coef=1.0):

    detector = cv2.CascadeClassifier('./dataset/haarcascade_frontalface_default.xml')
    face_zone = detector.detectMultiScale(frame)
    if len(face_zone) < 1:
        print("ERROR: No Face Detected")
        face_box_coor = [0, 0, frame.shape[0], frame.shape[1]]
    elif len(face_zone) >= 2:
        face_box_coor = np.argmax(face_zone, axis=0)
        face_box_coor = face_zone[face_box_coor[2]]
        print("Warning: More than one faces are detected(Only cropping the biggest one.)")
    else:
        face_box_coor = face_zone[0]
    if use_larger_box:
        face_box_coor[0] = max(0, face_box_coor[0] - (larger_box_coef - 1.0) / 2 * face_box_coor[2])
        face_box_coor[1] = max(0, face_box_coor[1] - (larger_box_coef - 1.0) / 2 * face_box_coor[3])
        face_box_coor[2] = larger_box_coef * face_box_coor[2]
        face_box_coor[3] = larger_box_coef * face_box_coor[3]
    return face_box_coor

def predict_vitals():

    frame_depth = 10
    kam_device = torch.device("cuda")  # Use CUDA device
    TSCAN_model = TSCAN(frame_depth=frame_depth, img_size=72).to(kam_device)

    # Load the saved state_dict
    state_dict = torch.load('final_model_release/UBFC_TSCAN.pth')

    # Create a new state_dict with modified keys
    new_state_dict = {}
    for key, value in state_dict.items():
        if key.startswith('module.'):
            new_key = key[len('module.'):]
        else:
            new_key = key
        new_state_dict[new_key] = value

    # Use the new_state_dict in your model
    TSCAN_model.load_state_dict(new_state_dict)
    TSCAN_model.eval()
    print(' Pre-trained Model loaded ')

    vid_path = 'my_vid.mp4'

    frames = read_video(vid_path)
    frames_clips = preprocess(frames)
    frames_clips = np.squeeze(frames_clips, axis=0)
    frames_clips_transposed = np.transpose(frames_clips, (0, 3, 1, 2))
    data = np.float32(frames_clips_transposed)
    data_tnsr = torch.from_numpy(data)
    data_tnsr = [data_tnsr.to](http://data_tnsr.to/)(kam_device)
    num_of_gpu = 1
    base_len = num_of_gpu * frame_depth
    ND, C, H, W = data_tnsr.shape
    data_tnsr = data_tnsr.view(ND, C, H, W)
    data_test = data_tnsr[:(ND) // base_len * base_len]
    print('data_test shape:', data_test.shape)

    with torch.no_grad():
        pred_ppg_test = TSCAN_model(data_test)
        print('pred_ppg_test:', pred_ppg_test)

if __name__ == "__main__":
    predict_vitals()
    
    # ********************* Output ****************************
    
     Pre-trained Model loaded
data_test shape: torch.Size([300, 6, 72, 72])
pred_ppg_test: tensor([[1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098],
        [1.0098]], device='cuda:0')
type pred_ppg_test: <class 'torch.Tensor'>
shape pred_ppg_test: torch.Size([300, 1])

Process finished with exit code 0

**Comment by yahskapar** [comment]
Hi @Changezi001,

You could try to better match the trainer code in `TscanTrainer.py` and see if that resolves the issue that you are seeing. Again, I recommend doing this or alternatively integrating your custom code into your fork of the toolbox, rather than taking fragments of code for a new function like `predict_vitals()`.

You mentioned you are trying to run this custom code of yours, using fragments of code from this toolbox, on your own videos. Can you try running your custom code on a video from an existing, commonly used dataset, such as the UBFC-rPPG dataset for example? That may also be a good point of investigation.

**Comment by yahskapar** [comment]
Closing this as there doesn't seem to be any further discussion. @Changezi001, please let us know if you're still having issues with your custom code. I also recommend you try to integrate changes you'd like to make to a branch of your own forked version of the toolbox rather than taking fragments of code from the toolbox and trying to get it all to work in a new, potentially more complicated codebase.
