### ISSUE TITLE
Can we infer the pre-trained model on macbook? (only cpu available)

### ISSUE THREAD

**Issue by KenTee** [ubicomplab/rPPG-Toolbox#167]
First, thank you for provide such useful toolbox for rPPG field.

As title, I am currently experiment with TSCAN model by using UBFC dataset on my macbook. In order to run model on cpu:

1. I set the DEVICE from 'cuda: 0' to 'cpu' in _PURE_UBFC-rPPG_TSCAN_BASIC.yaml_
2. I try to load the model with the following change in _TscanTrainer.py_:

- In the test function, I have modified the load model method from: _self.model.load_state_dict(torch.load(self.config.INFERENCE.MODEL_PATH))_ to _self.model.load_state_dict(torch.load(self.config.INFERENCE.MODEL_PATH, map_location=torch.device(self.device)))_

My questions are:
1. Except the above modification, is there anything left I need to modify to run model on cpu?
2. When run model on cpu, will the infer result be influenced?

**Comment by yahskapar** [comment]
Hi @KenTee,

I think you've already got some form of CPU-only inference going based on your other issues that are open (#173, #179), so I'll go ahead and close this issue and note that we do plan on adding some kind of CPU-only inference support in the coming months. If you run across any other problems, feel free to make a new issue.
