### ISSUE TITLE
Is it possible that the predict heartrate is exactly same as groundtruth heartrate?  

### ISSUE THREAD

**Issue by KenTee** [ubicomplab/rPPG-Toolbox#173]
I am currently experiment with UBFC dataset (subject10 ~ subject14) with _PURE_UBFC-rPPG_TSCAN_BASIC.yaml_. I have slightly modified the yaml file as follow:
1. Set **_METRICS_** to ['MAE','RMSE']
2. Set the **_DO_PREPROCESS_** to True.
3. Set my own **_DATA_PATH_** and **_CACHED_PATH_**.
4. Set the **_DEVICE_** to cpu.

When call the _calculate_metrics()_ function, I try to inspect the variables of **_gt_hr_fft_all_** and **_predict_hr_fft_all_**, and found the result as follow:

gt_hr: [**119.53125**    **128.3203125**   69.43359375 **109.86328125**  77.34375   ], 
pred_hr: [**119.53125**    **128.3203125**   67.67578125 **109.86328125**  70.3125    ]
FFT MAE (FFT Label): 1.7578125 +/- 1.2178482240718669
FFT RMSE (FFT Label): 3.241246098267031 +/- 8.72207385201761

The output gt/pred hr of subject10, subject11 and subject13 are exactly the same, is it possible?

**Comment by McJackTang** [comment]
That is possible for the same prediction as the ground truth. Since we got the hr results from the FFT of predicted PPG, if the PPG frequency is the same then the hr should be the same.

**Comment by girishvn** [comment]
Hi @KenTee, 

@McJackTang is correct. 

a little additional explanation. The discrete fourier transform (implemented with the FFT) converts a signal into a number of DISCRETE (not continuous) frequency values. For this reason slightly different continuous frequencies may be binned into the same discrete frequency values. The size of these frequency bins is determined by the length of the Fourier transform used (NFFT).  For this reason, as the frequencies are discretized, two Fourier transforms of equal length will have the same frequency bins. 

Thus, though is may seem unlikely, it is quite possible for predicted FFT values to be the exact same as the ground truth frequency. 

Hope this helps.

**Comment by yahskapar** [comment]
Hi @KenTee920806,

> With the default YAML setting, when USE_SMALLER_WINDOW is set to False, does it mean that the window size we use to predict heart rate (hr) is the total number of frames in the current video? With this setting, we only obtain one hr result per video. How should I interpret the output hr result? Is it the mean hr of the entire video?

Yes, when `USE_SMALLER_WINDOW` is `False`, the whole video (i.e., all of the frames) is used in one pass to estimate the heart rate. Meaning, if you evaluate 42 videos as in the case of UBFC-rPPG, you will have 42 ground truth heart rates and 42 predicted heart rates. Also yes, the output heart rate result is effectively the mean heart rate of the entire video in that case.

> If I set USE_SMALLER_WINDOW to True and WINDOW_SIZE to 10, does it mean that I can obtain the predicted hr result every 10 seconds? If so, why are the output results of gt_hr_fft_all and predict_hr_fft_all constant values?

Not quite "every" 10 seconds, but rather you will get a mean HR for every 10 second window of the video, and said window will be compared to the corresponding 10 second window of the provided ground truth. Does that make sense? I'm not sure what you mean by the output results being constant values - they should be the aforementioned mean HR values per window. For example, If I were to select a window size that's basically half the video length in the case of UBFC-rPPG, I would end up having 84 ground truth heart rates and 84 predicted heart rates.

> If I have misunderstood the use of USE_SMALLER_WINDOW, how can I obtain the output hr result for every 10 seconds or for specific seconds that I want?

Unless we have a different understanding of "every 10 seconds" here, I htink `USE_SMALLER_WINDOW` is doing what you want it to, it's just that the default usage of `USE_SMALLER_WINDOW` in the toolbox simply influences the reported metric results. If you want the more granular information you seek with the mean HR result after every 10 seconds, simply continue doing what you have been doing with printing out the `predicted_hr_fft_all` variable.

I think part of your confusion may be with each the constant values you saw with subject 10, but that could just be because it's a fairly constant heart rate throughout the video. Maybe try another subject's video?

**Comment by KenTee** [comment]
@yahskapar @girishvn  Thank you for the explanation!

> Not quite "every" 10 seconds, but rather you will get a mean HR for every 10 second window of the video, and said window will be compared to the corresponding 10 second window of the provided ground truth. Does that make sense? I'm not sure what you mean by the output results being constant values - they should be the aforementioned mean HR values per window. For example, If I were to select a window size that's basically half the video length in the case of UBFC-rPPG, I would end up having 84 ground truth heart rates and 84 predicted heart rates.

Yes, it make sense. For example, if I run on a 100s length video (30fps), with 10s window size, I will get 10 hr predict result. With 20s window size, I will get 5 hr predict result.  And each of the hr predict result can be interpret as the mean hr of the 10/20s (300/600 frames) window size. Correct me if I explain incorrectly. 

I would like to ask additional questions regrading this issue.

1. What is the minimum window size can we use for predict hr, is it 1s? And what is the minimum window size is recommended to use to predict hr to get a better reliable predict result?
2. With current setting, the window size is no overlapping with each other. Can the window size perform like sliding window method, continuous output predict result instead of waiting the window size being fullfill to output predict result. I ask this question because I am thinking whether this toolbox can be use for real time hr monitor application.


> I think part of your confusion may be with the constant values you saw with subject 10, but that could just be because the video itself has a fairly constant heart rate throughout. Maybe try another subject's video?

I have tried to experiment with different subjects, different window sizes and different evaluation method, but the output result seems to be constant. Following are part of my experiment results with FFT/ peak detection evaluation method:

**Subject12 - peak detection with input data shape before chunk: (1989, 72, 72, 6)**
- 1s window size 
```
gt_hr: [69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527
 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527], 
pred_hr: [73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918
 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918]
Peak MAE (Peak Label): 4.075086537403635 +/- 0.0
PEAK RMSE (Peak Label): 4.075086537403635 +/- 0.0
```

- 10s window size
```
gt_hr: [69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527 69.69540527], 
pred_hr: [73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918 73.7704918]
Peak MAE (Peak Label): 4.075086537403635 +/- 0.0
PEAK RMSE (Peak Label): 4.075086537403635 +/- 0.0
```

- 20s window size
```
gt_hr: [69.69540527 69.69540527 69.69540527 69.69540527], 
pred_hr: [73.7704918 73.7704918 73.7704918 73.7704918]
Peak MAE (Peak Label): 4.075086537403635 +/- 0.0
PEAK RMSE (Peak Label): 4.075086537403635 +/- 0.0
```

- USE_SMALLER_WINDOW: False
```
gt_hr: [69.69540527], pred_hr: [73.7704918]
Peak MAE (Peak Label): 4.075086537403635 +/- 0.0
PEAK RMSE (Peak Label): 4.075086537403635 +/- 0.0
```

**Subject14 - FFT with input data shape before chunk: (1993, 72, 72, 6)**
- 1s window size
```
gt_hr: [77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375
 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375
 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375
 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375
 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375
 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375
 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375
 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375
 77.34375 77.34375], 
pred_hr: [70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125
 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125
 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125
 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125
 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125
 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125
 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125
 70.3125 70.3125 70.3125]
FFT MAE (FFT Label): 7.03125 +/- 0.0
FFT RMSE (FFT Label): 7.03125 +/- 0.0
```

- 10s window size
```
gt_hr: [77.34375 77.34375 77.34375 77.34375 77.34375 77.34375 77.34375], 
pred_hr: [70.3125 70.3125 70.3125 70.3125 70.3125 70.3125 70.3125]
FFT MAE (FFT Label): 7.03125 +/- 0.0
FFT RMSE (FFT Label): 7.03125 +/- 0.0
```

- 20s window size
```
gt_hr: [77.34375 77.34375 77.34375 77.34375], 
pred_hr: [70.3125 70.3125 70.3125 70.3125]
FFT MAE (FFT Label): 7.03125 +/- 0.0
FFT RMSE (FFT Label): 7.03125 +/- 0.0
```

- USE_SMALLER_WINDOW: False
```
gt_hr: [77.34375], pred_hr: [70.3125]
FFT MAE (FFT Label): 7.03125 +/- 0.0
FFT RMSE (FFT Label): 7.03125 +/- 0.0
```

**Comment by yahskapar** [comment]
I think there is still some major misunderstandings here, which I'll try to address below. I will also go ahead and close this issue since I see #179 is up and likely more suitable for subsequent discussion given the overlap in topics.

> Yes, it make sense. For example, if I run on a 100s length video (30fps), with 10s window size, I will get 10 hr predict result. With 20s window size, I will get 5 hr predict result. And each of the hr predict result can be interpret as the mean hr of the 10/20s (300/600 frames) window size. Correct me if I explain incorrectly.

I'm confused where you are getting "10s windows size" translating to "10 hrs prediction result". If you run on a 100s length video with a 10s window size, you simply will get 10 heart rate measurements corresponding to the the 10 windows that 100s length video would be broken up into. You are not using the window size as some way to extend the video.

> What is the minimum window size can we use for predict hr, is it 1s? And what is the minimum window size is recommended to use to predict hr to get a better reliable predict result?

10 seconds is the minimum window size that I'd recommend to use to predict heart rate, but it's debatable that would lead to a more reliable prediction. Generally speaking, it's best to just use the entire video length if you can and assuming your videos aren't too long (e.g., on the order of many minutes).

> With current setting, the window size is no overlapping with each other. Can the window size perform like sliding window method, continuous output predict result instead of waiting the window size being fullfill to output predict result. I ask this question because I am thinking whether this toolbox can be use for real time hr monitor application.

A sliding window that overlaps could definitely be a feature in the future, but currently there are no immediate plans for taht and, as you said, the current smaller window size utility does not allow for an overlap between window segments.

**Comment by yahskapar** [comment]
Closing this to continue discussion on #179.

**Comment by Dylan-H-Wang** [comment]
> 

Hi,
Could you further explain what is "beat-to-beat timing". In other words,
 when should we choose FFT or peak detection for the inference?

**Comment by Dylan-H-Wang** [comment]
> Following on w/ what @yahskapar said: The constant value HR may because of the following:
> 
> A window of 10s, and a FS of 30fps, results in 10*30 = 300 samples in the window (used for FFT). An FFT on the 300 samples results in a max describable frequency increment of of 0.1Hz (30 / 300). 0.1Hz = 6bpm. They if the HR stays within a 6bpm rate between each 10s chunk, the result FFT output will be identical.
> 
> This is why longer videos are often used to calculate the HR, as a longer FFT results in higher frequency granularity. For better beat-to-beat timing a peak detection method may work better.
> 
>     * Girish

Hi @girishvn ,
Could you further explain what is "beat-to-beat timing". In other words,
when should we choose FFT or peak detection for the inference?
