### ISSUE TITLE
Has anyone successfully obtained reasonable results from supervised neural models on the UBFC-rPPG dataset or own recorded video?

### ISSUE THREAD

**Issue by KenTee** [ubicomplab/rPPG-Toolbox#179]
Hi,

I am currently experimenting with supervised neural models on my Mac (CPU only). I have tried using the TSCAN and DeepPhys models to test the UBFC-rPPG dataset. However, I am facing the following problems:

1. The inference time of the model is very slow, taking approximately 30 seconds for each test video to output predicted results (excluding preprocessing time). Could you please advise me on how to speed up the inference speed of the model? Does the length of the video affect the inference time? For example, if I input a 1-minute video and a 10-minute video, will the model's inference time be different?
2. The output ground truth and predicted results are always constant values. Regardless of the models I try, the subjects I use, or changing the evaluation window size, I always obtain constant HR (Heart Rate) values. I have no idea where to trace the issues. Could someone provide me with some guidance?
3. If someone has not encountered the above problems, could you please share how you have achieved that? I would greatly appreciate it!

Thanks.

**Comment by girishvn** [comment]
Hi @KenTee 

W/ regards to your questions. Training and inference jobs are ideally run w/ access to a GPU, because CPU inference and training are quite slow. 

1. Inference for different input length segments will take different amounts of time. A 10-min video will take around 10x the inference time as that of a 1min video. It should also be noted that as longer inputs result in higher frequency FFT resolution, longer videos may exhibit slightly better inference results. 

2. Let me look into this and see if there is a bug in the implementation. If not it may be because the window size being used for inference is too small.

**Comment by KenTee** [comment]
Hi @girishvn 

Thank you for the help! Just to let you know, I am experimenting with the UBFC-rPPG dataset, and each video has a length of around 1 minute. I have been trying out different window sizes (5, 10, 20, 30, 40, 50, USE_SMALLER_WINDOW=False), but the output results always remain constant regardless of the window size I use. I have never observed any variation in heart rate within a video, whether it's the ground truth values or the predicted values, and this is what confuses me the most.

Thanks.

**Comment by KenTee** [comment]
Hi @girishvn 

I found that we should set _DO_DYNAMIC_DETECTION_ and _USE_MEDIAN_FACE_BOX_ to true when running the preprocess in order to obtain a stable face ROI. Initially, I thought that the constant output value was due to non-face ROI inputs. However, even when the inputs consist of stable face ROI, the output results still remain constant.

**Comment by yahskapar** [comment]
Hi @KenTee,

I haven't looked into this thread or #173 too closely yet, but just wanted to let you know that I will take a look sometime toward the end of this week. I designed the smaller sampling window feature, so I may be able to better identify how you are running into some of the behavior that you noted to be strange.

Assuming you made a fork of this repo and are working with that, can you share your updated fork to make sure I have a full view of the code you are working with, including all code changes you have made?

**Comment by KenTee** [comment]
Hi @yahskapar,

Glad to hear that!

I have just committed the main update to my forked repo, without formatting, gitignore, imshow, and print statements. The repo can be found at [KenTee/rPPG-Toolbox](https://github.com/KenTee/rPPG-Toolbox).

With these minor updates, the output results always remain constant. You can try experimenting with the UBFC-rPPG dataset subject1, the output heart rate results for both ground truth and prediction are consistently **109.86328125**, regardless of the window size I change

**Comment by KenTee** [comment]
Hi @yahskapar @girishvn,

I have experimented with the UBFC subject1 ground_truth.txt. Instead of running the calculate_metrics() function inside the model test inference (using TscanTrainer.py), I directly calculate the heart rate using the peak detection method on the ppg signal from ground_truth.txt. As a result, I can finally observe the variation of heart rate values. Below is my experiment code:

1. The functions of read ppg signal and calculate heart rate.
```
def read_wave(bvp_file):
    """Reads a bvp signal file."""
    with open(bvp_file, "r") as f:
        str1 = f.read()
        str1 = str1.split("\n")
        bvp = [float(x) for x in str1[0].split()]
    return np.asarray(bvp)

def calculate_hr(ppg_signal, fs, window_size, use_bandpass=True):
    """Calculate heart rate based on PPG using peak detection."""
    if use_bandpass:
        # bandpass filter between [0.75, 2.5] Hz
        # equals [45, 150] beats per min
        [b, a] = butter(1, [0.75 / fs * 2, 2.5 / fs * 2], btype='bandpass')
        ppg_signal = filtfilt(b, a, np.double(ppg_signal))
    
    ppg_peaks, _ = find_peaks(ppg_signal)
    ibis = np.diff(ppg_peaks) / fs
        
    # Calculate heart rate over windows
    heart_rate = []
    start_index = 0
    while start_index + window_size <= len(ibis):
        window_ibi = ibis[start_index : start_index + window_size]
        window_heart_rate = 60 / np.mean(window_ibi)
        heart_rate.append(window_heart_rate)
        start_index += window_size
    
    return ppg_peaks, heart_rate
```

2. Calculate heart rate from ppg signal with sampling rate 30 and window size 10.
```
bvp_file = 'test_data/UBFC/subject1/ground_truth.txt'
ppg_signal = read_wave(bvp_file)

fs = 30
window_size = 10 # how many beats use to calculate the heart rate
ppg_peaks, heart_rate = calculate_hr(ppg_signal, fs, window_size, use_bandpass=False)
```

3. Visualize ground truth ppg signal with detected peaks.
```
fig, ax = plt.subplots(figsize=(20,5))
plt.title("PPG Signal with Detected Peaks")
plt.xlabel("Sample")
plt.ylabel("PPG Amplitude")
plt.plot(ppg_signal)
plt.plot(ppg_peaks, ppg_signal[ppg_peaks], 'ro')
```
<img width="1001" alt="Screen Shot 2023-06-28 at 4 15 09 PM" src="https://github.com/ubicomplab/rPPG-Toolbox/assets/62460680/6c31c84e-e696-461e-ba82-5c23c5a9b18b">


4. Visualize heart rate over time.
```
fig, ax = plt.subplots(figsize=(20,5))
time = np.arange(0, len(heart_rate) * window_size, window_size)
plt.title("Heart Rate over Time")
plt.xlabel("Time (s)")
plt.ylabel("Heart Rate (BPM)")
plt.plot(time, heart_rate)
```
<img width="1002" alt="Screen Shot 2023-06-28 at 4 15 16 PM" src="https://github.com/ubicomplab/rPPG-Toolbox/assets/62460680/d65c868e-e187-4916-a511-900f4ce406e0">


Is it the correct way to find the heart rate from the ppg signal?

When I attempted to examine the label (ground_truth) in the calculate_metrics() function, I noticed that the ppg signal appears to be dissimilar to the ground truth ppg signal obtained by directly reading from the text file. I understand that the difference in total frame length is a result of preprocessing using chunk length, but I cannot figure out why the pattern of the ppg signal seems unlikely. Is there exist another preprocessing step for the ground truth ppg signal?

```
def calculate_metrics(predictions, labels, config):
    """Calculate rPPG Metrics (MAE, RMSE, MAPE, Pearson Coef.)."""
    predict_hr_fft_all = list()
    gt_hr_fft_all = list()
    predict_hr_peak_all = list()
    gt_hr_peak_all = list()
    SNR_all = list()
    for index in tqdm(predictions.keys(), ncols=80):
        prediction = _reform_data_from_dict(predictions[index])
        label = _reform_data_from_dict(labels[index])
        
        # visualize
        fig, ax = plt.subplots(figsize=(20, 5))
        plt.title("PPG Signal with Detected Peaks")
        plt.xlabel("Sample")
        plt.ylabel("PPG Amplitude")
        plt.plot(label)
        plt.savefig("subject1_rppg.png")
```
<img width="1159" alt="Screen Shot 2023-06-28 at 4 29 05 PM" src="https://github.com/ubicomplab/rPPG-Toolbox/assets/62460680/fa9b7a54-aaf9-4be5-8e74-fe8eaf80956c">

Thanks.

**Comment by KenTee920806** [comment]
I noticed that it is because the ground truth label is preprocessed with the _"diff_normalize_label()"_ function. I apologize for not noticing it earlier.

**Comment by KenTee** [comment]
Hi @yahskapar @girishvn,

I think I have found the root cause of why I always get constant heart rate values no matter how I change my window size. Below is the original code of the _calculate_metrics(predictions, labels, config)_ function on the rppg-toolbox main branch.

```
def calculate_metrics(predictions, labels, config):
    """Calculate rPPG Metrics (MAE, RMSE, MAPE, Pearson Coef.)."""
    predict_hr_fft_all = list()
    gt_hr_fft_all = list()
    predict_hr_peak_all = list()
    gt_hr_peak_all = list()
    SNR_all = list()
    for index in tqdm(predictions.keys(), ncols=80):
        prediction = _reform_data_from_dict(predictions[index])
        label = _reform_data_from_dict(labels[index])

        video_frame_size = prediction.shape[0]
        if config.INFERENCE.EVALUATION_WINDOW.USE_SMALLER_WINDOW:
            window_frame_size = config.INFERENCE.EVALUATION_WINDOW.WINDOW_SIZE * config.TEST.DATA.FS
            if window_frame_size > video_frame_size:
                window_frame_size = video_frame_size
        else:
            window_frame_size = video_frame_size

        for i in range(0, len(prediction), window_frame_size):
            pred_window = prediction[i:i+window_frame_size]
            label_window = label[i:i+window_frame_size]

            if len(pred_window) < 9:
                print(f"Window frame size of {len(pred_window)} is smaller than minimum pad length of 9. Window ignored!")
                continue

            if config.TEST.DATA.PREPROCESS.LABEL_TYPE == "Standardized" or \
                    config.TEST.DATA.PREPROCESS.LABEL_TYPE == "Raw":
                diff_flag_test = False
            elif config.TEST.DATA.PREPROCESS.LABEL_TYPE == "DiffNormalized":
                diff_flag_test = True
            else:
                raise ValueError("Unsupported label type in testing!")
            
            if config.INFERENCE.EVALUATION_METHOD == "peak detection":
                gt_hr_peak, pred_hr_peak, SNR = calculate_metric_per_video(
                    prediction, label, diff_flag=diff_flag_test, fs=config.TEST.DATA.FS, hr_method='Peak')
                gt_hr_peak_all.append(gt_hr_peak)
                predict_hr_peak_all.append(pred_hr_peak)
                SNR_all.append(SNR)
            elif config.INFERENCE.EVALUATION_METHOD == "FFT":
                gt_hr_fft, pred_hr_fft, SNR = calculate_metric_per_video(
                    prediction, label, diff_flag=diff_flag_test, fs=config.TEST.DATA.FS, hr_method='FFT')
                gt_hr_fft_all.append(gt_hr_fft)
                predict_hr_fft_all.append(pred_hr_fft)
                SNR_all.append(SNR)
            else:
                raise ValueError("Inference evaluation method name wrong!")
```

In the second for loop, we retrieve the **_pred_window_** and **_label_window_** from the prediction and label arrays. From my perspective, we should calculate the heart rate based on **_pred_window_** and **_label_window_** instead of the original prediction and label arrays, as shown below:

**Before**:
```
gt_hr_peak, pred_hr_peak, SNR = calculate_metric_per_video(
                    prediction, label, diff_flag=diff_flag_test, fs=config.TEST.DATA.FS, hr_method='Peak')
```

**After**:
```
gt_hr_peak, pred_hr_peak, SNR = calculate_metric_per_video(
                    pred_window, label_window, diff_flag=diff_flag_test, fs=config.TEST.DATA.FS, hr_method='Peak')
```

After making the modification, I can observe variation in the heart rate values. However, I am unsure if this is the correct way to resolve the issue. Please correct me if I am mistaken.

Thanks.

**Comment by yahskapar** [comment]
Oh wow, this is definitely a bug that you found, @KenTee, thank you for looking into this. I'll make a PR for this shortly, it is indeed meant to be `pred_window` and `label_window`, similarly to how it currently is in `unsupervised_predictor.py`.

**Comment by yahskapar** [comment]
Addresed in #189, feel free to keep an eye on that PR and make a new issue if you run into any other weird behavior with the toolbox. Thanks again for spotting this, I'll go ahead and close this issue for now as the original problem should be resolved.
