### ISSUE TITLE
A question about COHFACEloader

### ISSUE THREAD

**Issue by guoguohello** [ubicomplab/rPPG-Toolbox#185]
Hello, I see that there is COHFACEloader in the dataloader folder, but there is no description of COHFACE dataset in the readme. Is there a problem with the COHFACEloader file, can I use it to load the COHFACE dataset?

**Comment by xliucs** [comment]
Hi, thanks for reaching out. Due to our bandwidth, we don't plan to add COFACE support in the near future. However, feel free make your PR if you are intereted in contributing to the toolbox. Thans.
