### ISSUE TITLE
How to use HSV instead of RGB in TS-CAN algorithm 

### ISSUE THREAD

**Issue by VikashPR** [ubicomplab/rPPG-Toolbox#186]
Hi, Can someone please help me this. I wanted to use HSV in TS-CAN algorithm with MMPD datasets, Instead of using RGB. I am using `PURE_MMPD_TSCAN_BASIC.yaml`

**Comment by KenTee** [comment]
Hi @VikashPR,

I am not familiar with the MMPD dataset. However, based on my understanding, you need to convert the frame color space from RGB to HSV inside the MMPDLoader's _read_mat()_ function. You can refer to the UBFCrPPGLoader's _read_video()_ function.

**Comment by yahskapar** [comment]
> Hi @VikashPR,
> 
> I am not familiar with the MMPD dataset. However, based on my understanding, you need to convert the frame color space from RGB to HSV inside the MMPDLoader's _read_mat()_ function. You can refer to the UBFCrPPGLoader's _read_video()_ function.

This is the way to go, definitely give it a try and let us know how it goes. You should be able to use OpenCV to do the actual conversion. An example of doing so can be found [here](https://www.tutorialspoint.com/how-to-convert-an-rgb-image-to-hsv-image-using-opencv-python).

**Comment by yahskapar** [comment]
Looks like you've succeeded in using HSV instead of RGB in your version of this repo [here](https://github.com/BMI-Lab-IITH/rPPG-Toolbox/commit/d395278d314defd82c6213a51961e07bd52db7a2), so I'm guessing this question of yours has been resolved @VikashPR. As a result, I'll go ahead and close this issue.

**Comment by VikashPR** [comment]
> Hi @VikashPR,
> 
> I am not familiar with the MMPD dataset. However, based on my understanding, you need to convert the frame color space from RGB to HSV inside the MMPDLoader's _read_mat()_ function. You can refer to the UBFCrPPGLoader's _read_video()_ function.

@KenTee Thank you. I was able to figure out how to change RGB to HSV in all datasets except MMPD. And changing so I was expecting to get better results, but I figured out that results with RGB are much better than HSV.

**Comment by VikashPR** [comment]
> Looks like you've succeeded in using HSV instead of RGB in your version of this repo [here](https://github.com/BMI-Lab-IITH/rPPG-Toolbox/commit/d395278d314defd82c6213a51961e07bd52db7a2), so I'm guessing this question of yours has been resolved @VikashPR. As a result, I'll go ahead and close this issue.

Yes, I was able to convert RGB to HSV @yahskapar Thank you 👍🏽
