### ISSUE TITLE
About the frame depth in TS_CAN

### ISSUE THREAD

**Issue by ZechenZed** [ubicomplab/rPPG-Toolbox#187]
Hi,

I was looking into the TS_CAN model and was curious about the word "frame depth". Does it refer to the number of frames in each mini-batch or something else?

**Comment by yahskapar** [comment]
"Frame depth" refers to the number of frames, or the window size, used in the temporal shift module that is a part of certain neural network architectures such as [TS-CAN](https://arxiv.org/abs/2006.03790) or [EfficientPhys](https://arxiv.org/abs/2110.04447). You can find a few more details on [TSM](https://arxiv.org/abs/1811.08383) and its implementation in TS-CAN by taking a look at the TS-CAN architecture source code as a part of this toolbox [here](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/neural_methods/model/TS_CAN.py#L27), as well as the  [TS-CAN paper](https://arxiv.org/abs/2006.03790) itself. 

The [EfficientPhys paper ](https://arxiv.org/abs/2110.04447) also has some more direct details on TSM in the context of that paper (note the details under section 3.2 on page 5 in particular).

**Comment by ZechenZed** [comment]
Thanks! That is really helpful!
