### ISSUE TITLE
About the Chunk length 

### ISSUE THREAD

**Issue by ZechenZed** [ubicomplab/rPPG-Toolbox#192]
Hi, 

I am curious about the chunk length in the BP4D_BP4D_PURE_TSCAN.yaml. Usually, in image processing, a chunk length could refer to the size of patches or regions of an image that are fed into the model. Is it the same here or something else? And, just so you know, the chunk length is the YAML file is 180.

**Comment by yahskapar** [comment]
Hi @ZechenZed,

Not quite - as described in the README [here](https://github.com/ubicomplab/rPPG-Toolbox#train--valid--test--unsupervised-data), the chunk length is the number of frames fed into the model (e.g., TS-CAN) to predict a PPG signal. In the case of the default of 180, that basically means a video is broken down into pre-processed chunks with 180 frames that are fed into the model to output a PPG signal. Then, at evaluation time (unless you're using a smaller window in your config) the chunks are reformed into the full video for evaluation.

Hope that helps!

**Comment by ZechenZed** [comment]
That totally makes sense. Thanks!
