### ISSUE TITLE
How do I calculate the algorithm executing time ?

### ISSUE THREAD

**Issue by VikashPR** [ubicomplab/rPPG-Toolbox#194]
Our research team wants to analyse the performance of all the supervised algorithms in terms of executing time. Can someone help us with this ?

**Comment by yahskapar** [comment]
I think you can use the `time` module and position the start and end times to record around [this](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/neural_methods/trainer/TscanTrainer.py#L75) line of code in the TS-CAN trainer, for example. That would at least give you an idea of how long it takes to run one batch of data through a supervised algorithm such as TS-CAN.

```
import time

# Rest of training code above

start_time = time.time()  # Record the starting time
pred_ppg = self.model(data)
end_time = time.time()  # Record the ending time

execution_time = end_time - start_time
print(f"Total model execution time: {execution_time:.2f} seconds")
exit()

# Rest of training code below
```

In the above example, you could remove the `exit()` call and just print the execution time each time, or average execution times or do whatever you need to do in order to analyze the performance of supervised algorithms with respect to execution time. I should note it's not clear to me how meaningful this analysis may be considering the implemented models in this repo may not be optimized for inference time (curious on @xliucs's or @girishvn's opinion).

**Comment by VikashPR** [comment]
> I think you can use the `time` module and position the start and end times to record around [this](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/neural_methods/trainer/TscanTrainer.py#L75) line of code in the TS-CAN trainer, for example. That would at least give you an idea of how long it takes to run one batch of data through a supervised algorithm such as TS-CAN.
> 
> ```
> import time
> 
> # Rest of training code above
> 
> start_time = time.time()  # Record the starting time
> pred_ppg = self.model(data)
> end_time = time.time()  # Record the ending time
> 
> execution_time = end_time - start_time
> print(f"Total model execution time: {execution_time:.2f} seconds")
> exit()
> 
> # Rest of training code below
> ```
> 
> In the above example, you could remove the `exit()` call and just print the execution time each time, or average execution times or do whatever you need to do in order to analyze the performance of supervised algorithms with respect to execution time. I should note it's not clear to me how meaningful this analysis may be considering the implemented models in this repo may not be optimized for inference time (curious on @xliucs's or @girishvn's opinion).

Thank you @yahskapar aren't we supposed to calculate the time in the ```main.py``` ? Calculating and noting which time will help us better understand how each algorithm performs with various datasets and different devices ?

**Comment by yahskapar** [comment]
> Thank you @yahskapar aren't we supposed to calculate the time in the `main.py` ? Calculating and noting which time will help us better understand how each algorithm performs with various datasets and different devices ?

It really depends on what you want to measure. If you want to measure how the algorithm (e.g., a model, such as TS-CAN or DeepPhys) performs with respect to inference time, then something along the lines of what I described in my previous reply makes sense to do. There shouldn't be any significant difference between measuring this time in light of various datasets as long as you report a meaningful measure such as per frame inference time (as the paper that introduces TS-CAN appears to do on page 7 of its paper [here](https://arxiv.org/abs/2006.03790)) and considering the pre-processing steps that are applied to the data, and it makes sense to me to pick different devices (GPUs, I assume, if we're talking about inference time) for measurement. Note that if you wanted to report something like a per frame inference time, and you have a batch size of 4 chunks with each chunk being 180 frames as specified in your config file, you can simply divide the measurement obtained in my previous reply by `(4*180)` to get a per frame inference time.

If you want to compare the pipeline at large, including components such as the dataloader, pre-processing, signal prediction from the model, and post-processing to ultimately get a heart rate value for example, that's different and shouldn't be referred to as an "algorithm". It should be referred to as the pipeline in my opinion.

**Comment by VikashPR** [comment]
> > Thank you @yahskapar aren't we supposed to calculate the time in the `main.py` ? Calculating and noting which time will help us better understand how each algorithm performs with various datasets and different devices ?
> 
> It really depends on what you want to measure. If you want to measure how the algorithm (e.g., a model, such as TS-CAN or DeepPhys) performs with respect to inference time, then something along the lines of what I described in my previous reply makes sense to do. There shouldn't be any significant difference between measuring this time in light of various datasets as long as you report a meaningful measure such as per frame inference time (as the paper that introduces TS-CAN appears to do on page 7 of its paper [here](https://arxiv.org/abs/2006.03790)) and considering the pre-processing steps that are applied to the data, and it makes sense to me to pick different devices (GPUs, I assume, if we're talking about inference time) for measurement. Note that if you wanted to report something like a per frame inference time, and you have a batch size of 4 chunks with each chunk being 180 frames as specified in your config file, you can simply divide the measurement obtained in my previous reply by `(4*180)` to get a per frame inference time.
> 
> If you want to compare the pipeline at large, including components such as the dataloader, pre-processing, signal prediction from the model, and post-processing to ultimately get a heart rate value for example, that's different and shouldn't be referred to as an "algorithm". It should be referred to as the pipeline in my opinion.

Thank you for clarity on this @yahskapar We really appreciate it.
