### ISSUE TITLE
can't see figures with viz_preprocessed_data.iypnb

### ISSUE THREAD

**Issue by pcloudddd** [ubicomplab/rPPG-Toolbox#195]
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/33437484/2eb1fd97-7e1f-4c88-8a10-7feeae1e7d90)
I think the displays are not uploaded while changing the chunk and frame index.
The figures are successfully displayed when I try to print them seperately, so there are no problem with the input files.
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/33437484/f7701949-7fc8-49c4-ab01-1743d9ca4138)
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/33437484/3bda8598-47fc-4f70-9469-3c77f253b550)

**Comment by yahskapar** [comment]
Hi @pcloudddd,

How exactly are you trying to run the Jupyter Notebook cells? I tested the notebook using VSCode and the [IPython kernel](https://ipython.readthedocs.io/en/stable/install/kernel_install.html). Are you using Google Colab to run the notebook?

I just tested the notebook in VSCode again and it seems to be working fine, although I did encounter a renderer-related error that I resolved by reloading the window as mentioned [here](https://github.com/microsoft/vscode-jupyter/discussions/12415). I also tested this in Google Colab [here](https://colab.research.google.com/drive/1CNEf1Q6uNlT-TcwRsdBsbEeG2AwMdPj8?usp=sharing) with a two chunks of data from the PURE dataset. It could be that there is some sort of issue in your notebook's kernel that is causing issues with rendering that aren't surfacing as visible error messages.

**Comment by yahskapar** [comment]
I'm going to go ahead and close this since it's been two weeks since another reply. @pcloudddd, please feel free to re-open this issue or make a new issue if problems persist, we are happy to help try and figure things out.

**Comment by pcloudddd** [comment]
Thanks for replying, @yahskapar. I used jupyter notebook and anaconda with an ubuntu20.04 computer to run the code.

**Comment by pcloudddd** [comment]
I think I can just use Google Colab for visualizing inputs.
