### ISSUE TITLE
Data loading issues

### ISSUE THREAD

**Issue by peizhengfu** [ubicomplab/rPPG-Toolbox#223]
Hello, I try to train on the COHFACE dataset and test on the UFBC-rppg dataset, modify the existing .yaml and save it as a new COHFACE_COHFACE_UBFC-rPPG_DEEPPHYS_BASIC.yaml file, and then I use this file for training , but I received the following error, how should I solve it.
Traceback (most recent call last):
  File "main.py", line 164, in <module>
    train_data_loader = train_loader(
  File "/root/autodl-tmp/rPPG-Toolbox-main/dataset/data_loader/COHFACELoader.py", line 49, in __init__
    super().__init__(name, data_path, config_data)
  File "/root/autodl-tmp/rPPG-Toolbox-main/dataset/data_loader/BaseLoader.py", line 67, in __init__
    self.preprocess_dataset(self.raw_data_dirs, config_data.PREPROCESS, config_data.BEGIN, config_data.END)
TypeError: preprocess_dataset() takes 3 positional arguments but 5 were given

**Comment by yahskapar** [comment]
Hi @peizhengfu,

As noted in our [datasets section](https://github.com/ubicomplab/rPPG-Toolbox#file_folder-datasets) of the README, we currently only support SCAMPS, UBFC-rPPG, PURE, BP4D+, UBFC-Phys, and MMPD. Checkout #185 for a few more details.

If you still want to try and use COHFACE with this toolbox, you will have to update the dataloader yourself for the time being. I recommend looking at other dataloaders (e.g., [UBFC-rPPG](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/dataset/data_loader/UBFCrPPGLoader.py)) for comparison and to better understand certain errors you might come across.
