### ISSUE TITLE
Preprocessed Data Path for BP4d+

### ISSUE THREAD

**Issue by amishparekh** [ubicomplab/rPPG-Toolbox#237]
Hi,
Due to huge size of the data of BP4D+, we are getting some ram issues.. Is it possible to share the data directory structure for preprocessed BP4d+ dataset. We wanted to try out the models and hence trying to tweak some codes as well, but not able to understand the structure of the preprocessed BP4d+.. I guess because of the RAM we are not able to load the data.

**Comment by yahskapar** [comment]
Hi @amishparekh,

I'm personally not too familiar with that dataset, but have you already referenced the information in the BigSmall repo on preprocessing [here](https://github.com/girishvn/BigSmall/tree/main/code#preprocessing-bp4d)? Also, for reference, the BP4D+ dataset's directory structure should be this as per our toolbox's README:

  ```
RawData/
   |   |-- 2D+3D/
   |       |-- F001.zip/
   |       |-- F002.zip
   |       |...
   |   |-- 2DFeatures/
   |       |-- F001_T1.mat
   |       |-- F001_T2.mat
   |       |...
   |   |-- 3DFeatures/
   |       |-- F001_T1.mat
   |       |-- F001_T2.mat
   |       |...
   |   |-- AUCoding/
   |       |-- AU_INT/
   |            |-- AU06/
   |               |-- F001_T1_AU06.csv
   |               |...
   |           |...
   |       |-- AU_OCC/
   |           |-- F00_T1.csv 
   |           |...
   |   |-- IRFeatures/
   |       |-- F001_T1.txt
   |       |...
   |   |-- Physiology/
   |       |-- F001/
   |           |-- T1/
   |               |-- BP_mmHg.txt
   |               |-- microsiemens.txt
   |               |--LA Mean BP_mmHg.txt
   |               |--LA Systolic BP_mmHg.txt
   |               |-- BP Dia_mmHg.txt
   |               |-- Pulse Rate_BPM.txt
   |               |-- Resp_Volts.txt
   |               |-- Respiration Rate_BPM.txt
   |       |...
   |   |-- Thermal/
   |       |-- F001/
   |           |-- T1.mv
   |           |...
   |       |...
   |   |-- BP4D+UserGuide_v0.2.pdf
```
Not sure if that helps. @girishvn should be able to reply back to this issue when he has time to.

**Comment by girishvn** [comment]
Hi @amishparekh, 

Sorry for the late reply. 
As @yahskapar mentioned, the above is the directory structure of the BP4D+ dataset

The preprocessed data directory structure of BP4D+ is very similar to that of the other datasets in this tool box. 
It is as follows:

BP4D_BigSmall_Preprocessed_DataDir
|        |-- F001T1_input0.pickle
|        |-- F001T1_label0.npy
|        |-- M001T8_input0.pickle
|        |-- F001T8_label0.npy
|        |-- F001T10_input0.pickle
|        | ...

Note that for BP4D+ the input file is a pickle format - a dictionary holding the video frames and the corresponding labels values.

**Comment by girishvn** [comment]
Hope the above helped. Closing this issue - feel free to open it if something comes up.
