### ISSUE TITLE
可以添加VIPL-HR数据集吗

### ISSUE THREAD

**Issue by litengfeigithub** [ubicomplab/rPPG-Toolbox#238]
可以添加VIPL-HR数据集吗

**Comment by yahskapar** [comment]
Hi @litengfeigithub,

We do not have any current plans to add the VIPL-HR dataset, but if you're interested in using it you should be able to add it yourself by referencing [this section](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#open_file_folder-adding-a-new-dataset) of the README and the [existing dataloaders](https://github.com/ubicomplab/rPPG-Toolbox/tree/main/dataset/data_loader).

Best of luck!

---ChatGPT4-translated version---

我们目前没有计划添加VIPL-HR数据集，但如果您有兴趣使用它，您应该可以通过参考[这个部分](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#open_file_folder-adding-a-new-dataset)的README和[现有的数据加载器](https://github.com/ubicomplab/rPPG-Toolbox/tree/main/dataset/data_loader)自行添加。

顺祝商祺
