### ISSUE TITLE
Missing averaging of appearance branch input frames for MTTS-CAN model

### ISSUE THREAD

**Issue by bulbarb** [ubicomplab/rPPG-Toolbox#239]
Hello, 

in the [original implementation of the MTTS-CAN](https://github.com/xliucs/MTTS-CAN/blob/89ffe818e1701ebcc156d4193657258e506eb781/code/data_generator.py#L154C1-L162C51) and TS-CAN model and in the corresponding paper, an averaging of the input frames for the appearance branch is performed. However, after looking closely at this repository, I could not find a corresponding implementation of it. When I look at the input data for the MTTS-CAN model in the debugger, no averaging of the appearance branch input data seems to have been performed there either. Instead, all standardized input frames are processed in the appearance branch. May there be an incorrect implementation of the data preprocessing for the appearance branch or am I missing something?

**Comment by xliucs** [comment]
Hi @bulbarb ， thanks for your interests. The purpose of averaging input frames is mainly for improving effiency. To simplfy t he implementation, we did not this step in this toolbox.

**Comment by bulbarb** [comment]
Alright, that seems reasonable. Thanks a lot for the quick reply.
