### ISSUE TITLE
Opencv reports insufficient memory to read data.

### ISSUE THREAD

**Issue by Wangzzy52** [ubicomplab/rPPG-Toolbox#242]
Preprocessing dataset...
  0%|                                                                                                                                | 0/6 [00:00<?, ?it/sP 
rocess Process-6:
Traceback (most recent call last):
  File "D:\zh-TW\An\envs\rppg-toolbox\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\zh-TW\An\envs\rppg-toolbox\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "e:\桌面\rPPG-Toolbox-main\dataset\data_loader\PURELoader.py", line 108, in preprocess_dataset_subprocess
    frames = self.read_video(
  File "e:\桌面\rPPG-Toolbox-main\dataset\data_loader\PURELoader.py", line 136, in read_video
    img = cv2.imread(png_path)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_8k9tw8n\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 921600 bytes in function 'cv::OutOfMemoryError'

**Comment by yahskapar** [comment]
Hi @Wangzzy52,

This is most likely some sort of issue with your computing environment. Can you share more details regarding your computing environment (e.g., operating system, amount of RAM you have, number of CPUs)? 

If you're on Linux, you can easily check how much CPU resources and RAM you're using with `top`, or alternatively `free -g` to focus on just RAM in gigabyetes (`-g`), and CPU information with `lscpu`.

**Comment by yahskapar** [comment]
This issue seems inactive, so I'll go ahead and close it. Hopefully you were able to figure this out in your computing environment @Wangzzy52.
