### ISSUE TITLE
PPG signal post-processing

### ISSUE THREAD

**Issue by xlsay** [ubicomplab/rPPG-Toolbox#252]
Hi, the model output is in PPG signals. How can it be converted to corresponding heart rate values? Thanks.

**Comment by girishvn** [comment]
I suggest taking a look at how `/evaluation /post_process.py` uses the function `calculate_metric_per_video` to calculate the HR. It should be noted that many of the deep-models output a diffed pulse signal (equal to applying `np.diff` to pulse signal).

Best

**Comment by xlsay** [comment]
> I suggest taking a look at how `/evaluation /post_process.py` uses the function `calculate_metric_per_video` to calculate the HR. It should be noted that many of the deep-models output a diffed pulse signal (equal to applying `np.diff` to pulse signal).
> 
> Best

Ok, thank you very much!
