### ISSUE TITLE
Question about intra-dataset experiments

### ISSUE THREAD

**Issue by Dylan-H-Wang** [ubicomplab/rPPG-Toolbox#255]
Hi,

Is there any specific reason that why you only did cross-dataset experiments. I think intra-dataset experiments can be useful in some cases.

Thanks

**Comment by girishvn** [comment]
Hi @Dylan-H-Wang ,

Yes you are right, intra-dataset experiments can be useful in some cases. However, the standard in rPPG literature is to evaluate using cross dataset experiments. As this toolbox benchmarks using common evaluations from the community, we primarily use cross dataset evals.

Hope this clarifies things!

**Comment by Dylan-H-Wang** [comment]
Ok, thank you for the clarification!
