### ISSUE TITLE
Inference for BigSmall pretrained models for testing BP4d+ dataset

### ISSUE THREAD

**Issue by amishparekh** [ubicomplab/rPPG-Toolbox#259]
@girishvn 
Getting BP4d+ dataset for me in form of hard-drive is tough to get..  I wanted to test how BP4d+ dataset fares compared to other datasets.. So thought of using Inference files (Specifically Ones for BigSmall pretrained model files) but to inference I would need reference to what exactly is in preprocessed data files. The whole purpose is to understand how varied data (skin colour, etc would affect the inference in real time videos) Any idea how to go about this?
Thank you for sharing your work...
Thanks!

**Comment by girishvn** [comment]
Hi @amishparekh if you are focused specifically on ppg with respect to skin-tone I would potentially focus on a different PPG data-set. 

BP4D+  does not contain PPG ground truth signals, and further does not have significant environmental changes from video to video. I would suggest PURE or UBFC-rppg instead.

**Comment by amishparekh** [comment]
Okay.. Thanks!
