### ISSUE TITLE
A bug in the code for the yaml related to Physformer

### ISSUE THREAD

**Issue by OliverDOU776** [ubicomplab/rPPG-Toolbox#260]
Hi there,

thanks for the great repo! However, in all yaml files related to Physformer, seems the Model name is set to be Tscan :)

**Comment by McJackTang** [comment]
Yes, I found that bug too, we will fix this problem in the next push version. Thanks for reminder!

**Comment by yahskapar** [comment]
This will be fixed in #261 - as Jack said, thanks for the heads up!
