### ISSUE TITLE
DEVICE is set to cuda: 5, but the result still runs on GPU0

### ISSUE THREAD

**Issue by 408550969** [ubicomplab/rPPG-Toolbox#264]
Hi,I modified the DEVICE: to cuda: 5 under UBFC-rPPG_UBFC-rPPG-PURE EFFICIENTPHYS.yaml, but from the results, it still runs on GPU0. Why is this?

**Comment by yahskapar** [comment]
Hi @408550969,

Can you try using `CUDA_VISIBLE_DEVICES` while executing your python commands, for example in your case to use just the GPU with the ID 5:

```
CUDA_VISIBLE_DEVICES=5 python main.py --config_file ./configs/train_configs/UBFC-rPPG_UBFC-rPPG_PURE_EFFICIENTPHYS.yaml
```

You can also specify multiple devices (e.g., `0,1,2,3`). In the future we can try to make the config option more robust and usable the way you've tried to use it, but this may require some additional refactoring of the repo given how early that device binding needs to take place. For the time being doing what I suggested above should solve your issue.

**Comment by 408550969** [comment]
Thanks, it worked!
