### ISSUE TITLE
visualization issues

### ISSUE THREAD

**Issue by peizhengfu** [ubicomplab/rPPG-Toolbox#275]
Hello, when I use the visualization tool in the toolbox, I find that I can't see the video frame, and the spectrogram is different from the example, what is the reason for this?
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/50606839/7bb7e97e-450d-4c24-8573-86f1ea215a91)

**Comment by Dream999999** [comment]
You can try to see if this line of code can be displayed. Also, regarding the issue with your frequency domain graph, how many frames are each segment divided into for you? Mine is divided into 512 segments, and the distance between waveforms is also very close. You can try increasing the spacing to display it, which might be helpful.
![Uploading 屏幕截图 2024-07-17 161826.png…]()

**Comment by hanhongxiaozhanggui** [comment]
Have you solved this issue? I have the same question.

**Comment by yahskapar** [comment]
I will try to work on this sometime within the next week or two in order to make the visualization more robust across different environments. Stay tuned for more info on that, specifically on the latest issue regarding this (#318).
