### ISSUE TITLE
KeyError: 'Non-existent config key: TRAIN.DATA.PREPROCESS.CROP_FACE.BACKEND

### ISSUE THREAD

**Issue by peizhengfu** [ubicomplab/rPPG-Toolbox#276]
Hello, when running the code, the following error will always be reported, when I delete the key value of BACKEND: 'HC' in the configuration file, the code returns to normal, what is the reason?
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/50606839/f695d44f-b435-4d33-aefc-a212d5776cae)

**Comment by yahskapar** [comment]
Hi @peizhengfu,

This seems really strange, are you still running into this issue with a fresh copy of one of the existing config files and to make sure no additional characters or anything weird like that were introduced into your config file? It could be possible some misplaced characters could be causing issues with parsing the config after you edited it.

Let us know if you're still running into this issue, and if so, please share your full config file as is.

**Comment by yahskapar** [comment]
I'll go ahead and close this issue given the lack of a reply, but please re-open if this error persists for you, @peizhengfu.
