### ISSUE TITLE
how to create this comparison file

### ISSUE THREAD

**Issue by peizhengfu** [ubicomplab/rPPG-Toolbox#277]
Hello, I'm sorry to disturb you. I would like to know how to create this comparison file. I have added a new dataset but I am unsure about the origin of the data in this file.
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/50606839/9056f4d5-a316-4d59-8a8a-39f42bbd2f22)

**Comment by yahskapar** [comment]
Hi @peizhengfu,

I spoke about these files a bit in a past issue - #152. For the sake of benchmarking your new dataset, I wouldn't worry about these files. I'll bring them up for discussion and most likely we will remove them in the near future to avoid further confusion.

I'll go ahead and close this issue, but feel free to make a new one if you run into any trouble with using your new dataset with this toolbox.
