### ISSUE TITLE
the problem of BP4D+ dataset preprocessing

### ISSUE THREAD

**Issue by Harry2345** [ubicomplab/rPPG-Toolbox#281]
Thank you very much for the author excellent work, I am currently trying to reconstruct bigsmall, I saw the BP4D described in https://github.com/girishvn/BigSmall/blob/main/code/README.md , the pretreatment of the data set is complicated, Can directly use your provided by https://github.com/ubicomplab/rPPG-Toolbox/blob/main/dataset/data_loader/BP4DPlusBigSmallLoader.py in the toolbox Preprocessing BP4D+, is the result the same as the steps you stated in the readme?
Because only demo is provided in toolbox, I hope to reproduce the source code provided by the author. Is the author's code complete?

**Comment by girishvn** [comment]
Hi @Harry2345,

That is interesting. The code should be complete but it is possible that my most recent push has broken something. I will look into the preprocessing in the other repo.

For the time being you can use the pre-processing outlined in this repository. 
It should output the needed data format for BigSmall.

**Comment by girishvn** [comment]
Hi @Harry2345 I just confirmed there is a bug in that code. 
I'll get to fixing that sometime in the next few weeks.
Please use the dataloader / preprocessor found here.

Thanks
