### ISSUE TITLE
On the issue of facial cropping

### ISSUE THREAD

**Issue by moon-ligh** [ubicomplab/rPPG-Toolbox#282]
Hello, I see that almost all configuration files in the code will be set  USE_LARGE_FACE_BOX: True ,LARGE_BOX_COEF: 1.5.
The video after being cropped in this way is generally as follows:
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/64957185/39b72fe2-935c-4c7b-9b18-94741aac5a5f)
Besides the facial part, there are also background colors or shoulders. I'm curious why only the facial part is cropped out, like this:
![image](https://github.com/ubicomplab/rPPG-Toolbox/assets/64957185/908c13af-913f-456c-9d06-49ed92223b47)
What is the specific reason?

**Comment by girishvn** [comment]
This method is most useful for unsupervised methods / signal processing methods like CHROM / POS / etc, where cropping out background can result in higher SNRs.

This is less true for attention based models such as TSCAN and DeepPhys which learn to isolate the face through attention (however these may also benefit slightly from background crop).

**Comment by yahskapar** [comment]
I'll go ahead and close this issue since it seems like the original question was addressed, but feel free to create a new issue if anything else comes to mind. Thanks!
