### ISSUE TITLE
Regarding the issue of video data rate

### ISSUE THREAD

**Issue by moon-ligh** [ubicomplab/rPPG-Toolbox#285]
Hello,May I ask if the video on the UBFC dataset takes up a relatively large amount of space, with a video speed of 2188322kbps
![UBFC](https://github.com/ubicomplab/rPPG-Toolbox/assets/64957185/e2291a40-fc0e-4f81-8488-8089b08ce410)
However, the video I recorded myself has a speed of approximately 3000kbps.
![zijian](https://github.com/ubicomplab/rPPG-Toolbox/assets/64957185/e4cebb0f-24f4-4c7d-9fc2-77e685bd53c3)
In terms of the difference in video quality, how would it affect the results if I used pre trained weights on UBFC to predict my own videos? Can signals still be accurately predicted?

**Comment by yahskapar** [comment]
Hi @moon-ligh,

Typically speaking, lower quality videos with lower bitrates can make it harder to get a reasonable signal measurement, but we cannot really predict the performance difference aside from predicting it will get generally worse. I recommend you evaluate on your own videos as you mentioned and keep the compression differences in mind as a part of your analysis. You can also check out sections 9.5 of this [review article](https://arxiv.org/pdf/2111.11547) and some of the referenced work, including [this](https://opg.optica.org/boe/fulltext.cfm?uri=boe-12-1-494) for more details regarding the effects of compression.

**Comment by moon-ligh** [comment]
> Hi @moon-ligh,
> 
> Typically speaking, lower quality videos with lower bitrates can make it harder to get a reasonable signal measurement, but we cannot really predict the performance difference aside from predicting it will get generally worse. I recommend you evaluate on your own videos as you mentioned and keep the compression differences in mind as a part of your analysis. You can also check out section 9.5 of this [review article](https://arxiv.org/pdf/2111.11547) and some of the referenced work, including [this](https://opg.optica.org/boe/fulltext.cfm?uri=boe-12-1-494) for more details regarding the effects of compression.




Okay, thank you for your reply！

**Comment by yahskapar** [comment]
No problem!

Closing this issue now since the original question was answered, but feel free to make a new one if you have any other questions or run into problems with the toolbox.
