### ISSUE TITLE
How to estimate the SNR of a ppg signal when there is no true value?

### ISSUE THREAD

**Issue by 408550969** [ubicomplab/rPPG-Toolbox#291]
In actual testing, there is no true value ppg signal. How to estimate the SNR or similar indicators of a video stream so as to determine whether the heart rate value of this video stream is displayed

**Comment by girishvn** [comment]
Hi,

I would suggest writing code for a comb filter. 
This calculates the energy under the first and second harmonic. You can compare this against the energy under the rest of the frequency spectrum. 
This value should be proportional to SNR.

This requires taking the frequency spectrum of the predicted signal, and finding the lowest frequency peak for which there is a peak at the second harmonic.

This method is often times crude, and unless the prediction exhibits strong periodicity may not perform very well. 

Hope this helps.

**Comment by 408550969** [comment]
Based on your description, should I calculate the energy for the first and second harmonics under pxx_ppg or mask_pxx?

**Comment by jungyin** [comment]
> _calculate_fft_hr

Can you calculate SNR normally using this method? The rppg generated during my use is used to generate HR
Very unstable, may I ask if you are stable?
