### ISSUE TITLE
Experiment Result

### ISSUE THREAD

**Issue by TK-31** [ubicomplab/rPPG-Toolbox#308]
It's great to provide cross-dataset experimental results! Could you also provide intra-dataset test results additionally?

**Comment by yahskapar** [comment]
Hi @TK-31,

We unfortunately don't have any plans to do this ourselves anytime soon, though we may plan to add such results (perhaps with more datasets in general) in the future. If you happen to collect such results yourself, feel free to share them and we would be happy to link to them (whether it's an academic paper or just a quick report of some kind) in this repo. Thanks.
