### ISSUE TITLE
What is the relationship between bvp signal and ppg signal?

### ISSUE THREAD

**Issue by jungyin** [ubicomplab/rPPG-Toolbox#311]
I am learning about this area of knowledge, but based on what I have found online, it seems that bvp and ppg are the same thing, or at least similar. In addition, PPG has specialized equipment for data collection. How does BVP collect data?

**Comment by girishvn** [comment]
Hi @jungyin 

BVP and PPG are very similar (and are often used interchangeably).
BVP (blood volume pulse) refers the pulse detected as function of fluctuations in volume (eg. when capillaries dilate the volume of blood changes).

PPG (photoplethysmography) detects the blood volume pulse through the use of optical sensing.

Technically PPG is the method for detecting the BVP phenomena, but there is little distinction in computing literature.

**Comment by jungyin** [comment]
> Hi @jungyin
> 
> BVP and PPG are very similar (and are often used interchangeably). BVP (blood volume pulse) refers the pulse detected as function of fluctuations in volume (eg. when capillaries dilate the volume of blood changes).
> 
> PPG (photoplethysmography) detects the blood volume pulse through the use of optical sensing.
> 
> Technically PPG is the method for detecting the BVP phenomena, but there is little distinction in computing literature.

I noticed that the values of bvp are usually very large, ranging from a few hundred to positive and negative, while the values of ppg signals are much smaller compared to others, probably in single digits, and there are no negative numbers. However, it seems that after pre-processing, they become rppg signals with positive and negative values, and the value range is only in single digits?
