### ISSUE TITLE
The heart rate I calculated fluctuates a lot.

### ISSUE THREAD

**Issue by jungyin** [ubicomplab/rPPG-Toolbox#313]
I am trying to calculate the heart rate using the rppg signal I calculated, but the calculated hr deviation value is very large. It may be 100 last time and 50 next time, and the real value is 70. I tried to use heartpy to calculate the bpm, and the value obtained was also very large. What should I do in this situation?

**Comment by jungyin** [comment]
In addition, I have bandpass filtered or not filtered the rppg value, and obtained the heart rate through the _calculate_fft_hr method and the get_hr method respectively. The value obtained is either the same heart rate for anyone to measure, or it fluctuates rapidly and violently in a short period of time.

**Comment by yahskapar** [comment]
Hi @jungyin,

See my response on your other issue involving HeartPy [here](https://github.com/ubicomplab/rPPG-Toolbox/issues/319#issuecomment-2395259423).
