### ISSUE TITLE
I have a quetion about a class atribute

### ISSUE THREAD

**Issue by hanhongxiaozhanggui** [ubicomplab/rPPG-Toolbox#315]
I find a class atribute which named "self.preprocess_dataset_subprocess" is used in the function "multi_process_manager" of Class Baseloader. Does the atribute has been drop in the recentest version of your project?

**Comment by yahskapar** [comment]
Hi @hanhongxiaozhanggui,

Nope, the base class method and the override methods are still there and are used to create new processes as a part of the `multi_process_manager()` function. Note that function, `preprocess_dataset_subprocess()` is [implemented for each custom dataloader,](https://github.com/search?q=repo%3Aubicomplab%2FrPPG-Toolbox%20preprocess_dataset_subprocess&type=code) and [can be implemented for your own custom dataloader](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#open_file_folder-adding-a-new-dataset) if you wish.

Are you having trouble implementing your own custom dataloader? If not, did you run into some issue where the existing method implementations seem to be missing?
