### ISSUE TITLE
gpu selection problem

### ISSUE THREAD

**Issue by creaycoder** [ubicomplab/rPPG-Toolbox#317]
I set DEVICE:cuda1 in the configuration file. But running main.py always shows that the application is running with GPU0. What is the reason for this?
![d56ded6a850e89cf7ebd14793ba708d](https://github.com/user-attachments/assets/56acd26c-9263-4cb1-ad81-4f53818c40fd)
![212f9cea6f5066c71d95047535fa54f](https://github.com/user-attachments/assets/67fb03fb-deb1-487a-bbe8-cfce3cd90d3d)
![585cec338809f4ce50e5ee348ebef98](https://github.com/user-attachments/assets/f960f7a6-b8a3-4f37-a454-600d132f5117)

**Comment by yahskapar** [comment]
Hi @creaycoder,

I unfortunately don't even have a multi-GPU machine to reproduce and debug this properly - for the time being, I suggest using something like:

```
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --config_file ./configs/train_configs/PURE_PURE_UBFC-rPPG_TSCAN_BASIC.yaml
```

Prepending your python command with `CUDA_VISIBLE_DEVICES=` and then selecting the GPU IDs should work fine, and likely will be equivalent (and maybe a bit more convenient than editing a file) to your usage of `os.environ` that you commented out.
