### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by hanhongxiaozhanggui** [ubicomplab/rPPG-Toolbox#318]
Hello, when I use the visualization tool in the toolbox, I find that I can't see the video frame, and the spectrogram is different from the example.Then,when I select different files for visualization and switch about three times, I can no longer switch chunks.How should I solve this issue?
![屏幕截图 2024-09-22 134951](https://github.com/user-attachments/assets/99d2a8d0-fd7c-4556-86d3-0998834d74a8)
![屏幕截图 2024-09-22 135512](https://github.com/user-attachments/assets/144ceb6b-9a94-4b4f-b5d8-a04b6a839426)

**Comment by yahskapar** [comment]
This should be fixed as soon as #323 is reviewed and merged. Thanks for pointing this out, and please create a new issue if somehow that gets merged and this issue persists for you.
