### ISSUE TITLE
Is this repo compatible to be used on a macbook?

### ISSUE THREAD

**Issue by Niteesh-Kalangi** [ubicomplab/rPPG-Toolbox#320]
Whenever I try running the models locally on my own data, I keep getting this issue:

<img width="906" alt="Screenshot 2024-09-27 at 11 38 09 AM" src="https://github.com/user-attachments/assets/62a1dad4-72bd-4fee-98c5-be60e949e08e">

Here is my yaml config file:
<img width="738" alt="image" src="https://github.com/user-attachments/assets/fe139f30-8904-40eb-ba68-b4ec28ac94b8">
<img width="745" alt="image" src="https://github.com/user-attachments/assets/b0ca0be2-0a6d-4d00-87b9-ddfbd0600aea">

**Comment by yahskapar** [comment]
Hi @Niteesh-Kalangi,

When you went through the [repo setup](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#wrench-setup), did you run into any issues? Maybe try running through those setup instructions again and be sure to carefully observe the terminal output. I wonder if there's some sort of installation issue going on, perhaps with a specific library or two and with relation to newer MacBooks having their own, custom chip architecture (e.g., M1, M2, etc). 

Generally speaking, this repo should be compatible, though it's possible there's some kind of compilation-related mismatch going on with newer MacBooks. Pretty much all of the repo contributors have only developed and tested this repo's code on machines with some kind of Linux, and typically we've seen users of the repo use either Windows or Linux.

You can try installing something like [this](https://support.apple.com/en-us/102527) and looking up related information, assuming you do indeed have a newer MacBook with Apple's chip architecture.

**Comment by Niteesh-Kalangi** [comment]
Oh yeah, when I tried running the bash.sh script, this error popped up:
<img width="634" alt="image" src="https://github.com/user-attachments/assets/35c9d178-06fd-4397-8587-46ae9bd72f7e">

Thus, I originally removed the cudatoolkit part of the bash.sh script and followed the rest of the instructions. This could've been what caused my issue with the illegal hardware instructions. However, that still doesn't fix the fact that I can't seem to be able to install cudatoolkit. When looking online, I think the reason for this is that Mac is no longer compatible with cuda. Any work arounds you can think of?

**Comment by yahskapar** [comment]
Sorry, no workarounds come to mind. You can try maybe running everything using a VM with Linux, or maybe try SSHing into a Linux machine. I'm sure there's a way to maybe get it to work on MacOS with the newer architectures, but this particular toolbox can't explicitly provide support for that due to a lack of resources.

**Comment by yahskapar** [comment]
Feel free to follow-up here with any workarounds you find or additional information, but given my previous answer, for now I'll close this issue to keep the issues listing a bit cleaner.
