### ISSUE TITLE
viz_preprocessed_data ist not interactive

### ISSUE THREAD

**Issue by cvuus** [ubicomplab/rPPG-Toolbox#327]
Hello, 

first of all, thank you for this amazing toolbox. Currently, I am trying to apply the algorithms to my dataset. To do this I started with already implemented dataset to understand the toolbox. 

So I used the UBGC-rPPG dataset and ran the following command to gather preprocessed Data:

 python main.py --config_file ./configs/infer_configs/PURE_UBFC-rPPG_DEEPPHYS_BASIC.yaml

Next, I aimed to visualize the preprocessed data, so I changed the preprocessed data path in the viz_preprocessed_data.ipynb file. 

The output shows "44 input files and 44 label files detected".

However, the widgets are not responsive. I already tried to install jupyter labextension and other workarounds to enable the interactive display, but the output keeps being blank.

![Blank_Output](https://github.com/user-attachments/assets/dc47b999-386c-491b-b6e1-2ba8b654f75d)

There is no error code displayed. 

I am using the following jupyter version:
IPython          : 8.12.2
ipykernel        : 6.29.5
ipywidgets       : 8.1.5
jupyter_client   : 8.6.0
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
jupyterlab       : 4.2.5
nbclient         : 0.8.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.2.2
qtconsole        : 5.6.0
traitlets        : 5.14.3

Hope to hear from you soon.
Thank you and kind regards

EDIT: Now I see that the output is correctly displayed in the log, but not in the widget cells of the notebook

**Comment by yahskapar** [comment]
Hi @cvuus,

How are you trying to run this (e.g., in some desktop version of Jupyter Lab or something else)? If you're not using VSCode, can you please try using VSCode and making sure you're using the same conda environment as the toolbox when running the notebook (as pictured below, for example)? All you should have to do with VSCode is install the Jupyter extension pack and then re-use the same conda environment that was created for the toolbox in the [setup instructions](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#wrench-setup).

![Screenshot from 2024-11-02 12-04-45](https://github.com/user-attachments/assets/9768b07c-5e2d-4c37-85a4-4d87fadae5fc)

**Comment by yahskapar** [comment]
Closing because the lack of further discussion, but please do let us know if you continue having trouble with the visualizations, @cvuus. Thanks.
