### ISSUE TITLE
Use of ‘PURE_PURE_UBFC-rppg _EFFICIENTPHYS’

### ISSUE THREAD

**Issue by Fairy77ya** [ubicomplab/rPPG-Toolbox#334]
I am using the EfficientPhys model. Specifically, I use "PURE-PURE-UBFC-rPPG_EFFICIENTPHYS." I used both PURE and UBFC-rPPG datasets completely, and the model passed the 'Training' phase, but the following error occurred in the 'Testing' solution. I want to ask you, what's the reason? Have you ever met one?
![111](https://github.com/user-attachments/assets/cee74a73-db76-488d-ad50-77d96f3aca30)
![bd230d86ee5ac51771baf24dbc5af6a](https://github.com/user-attachments/assets/880734ab-72da-441e-b436-852d8f0dbf7b)

**Comment by yahskapar** [comment]
Hi @Fairy77ya,

Are you trying to use this toolbox without a GPU (i.e., CPU-only)? I've only ever seen that error before with folks trying to use the toolbox in a CPU-only fashion, which we don't explicitly support. You're welcome to try getting it to work based on a past issue in this toolbox that someone else posted, #176.

All the best,

Akshay

**Comment by yahskapar** [comment]
Closing this due to the lack of follow-up discussion, but please let us know if you have any further issues or confusion @Fairy77ya.
