### ISSUE TITLE
Environment setup issue

### ISSUE THREAD

**Issue by 3051485652** [ubicomplab/rPPG-Toolbox#340]
hope this message finds you well. I am reaching out regarding the [Project Name] repository. While setting up the environment as instructed, I encountered an issue during the installation of [specific package or dependency causing the issue, e.g., causal-conv1d]. The error message I received is:

error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /tmp/pip-install-4nd9oerq/causal-conv1d_ab21852e1fef4709b3d9f6f0f45b2e49/setup.py:77: UserWarning: causal_conv1d was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4nd9oerq/causal-conv1d_ab21852e1fef4709b3d9f6f0f45b2e49/setup.py", line 111, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined
      
      
      torch.__version__  = 2.1.2+cu121
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by yahskapar** [comment]
Do you have CUDA properly installed on your system? You can check by trying `nvcc --version`. If you don't have it installed, try installing CUDA first before trying the installation process again. 

The issue appears to be specific to your CUDA installation, but if you plan on running the toolbox CPU-only (which isn't explicitly supported by this toolbox, but has been done by others in the past, such as [here](https://github.com/ubicomplab/rPPG-Toolbox/issues/176)) and don't care about using PhysMamba, you can probably ignore the error and use other parts of the toolbox.

**Comment by 3051485652** [comment]
> Do you have CUDA properly installed on your system? You can check by trying `nvcc --version`. If you don't have it installed, try installing CUDA first before trying the installation process again.
> 
> The issue appears to be specific to your CUDA installation, but if you plan on running the toolbox CPU-only (which isn't explicitly supported by this toolbox, but has been done by others in the past, such as [here](https://github.com/ubicomplab/rPPG-Toolbox/issues/176)) and don't care about using PhysMamba, you can probably ignore the error and use other parts of the toolbox.

Thank you! I tried to install CUDA 12.1, but I found that my Ubuntu version is 24.04, which does not support CUDA 12.1.

**Comment by 3051485652** [comment]
Thank you for your help. I resolved the issue mentioned earlier, but it seems that a new problem has arisen during the final step of the installation, which has puzzled me for a long time. I would greatly appreciate your assistance if you could help me.
 Installed /home/liugenchao/anaconda3/envs/rppg-toolbox/lib/python3.8/site-packages/einops-0.8.0-py3.8.egg
Searching for tokenizers<0.21,>=0.20
Reading https://pypi.org/simple/tokenizers/
Downloading https://files.pythonhosted.org/packages/1a/98/0df883ea6201e35e286a97f5fb2a601bfb5b52e4165f7688a76e4553eeec/tokenizers-0.20.4.tar.gz#sha256=db50ac15e92981227f499268541306824f49e97dbeec05d118ebdc7c2d22322c
Best match: tokenizers 0.20.4
Processing tokenizers-0.20.4.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-v9xafx2t/tokenizers-0.20.4.tar.gz

> Do you have CUDA properly installed on your system? You can check by trying `nvcc --version`. If you don't have it installed, try installing CUDA first before trying the installation process again.
> 
> The issue appears to be specific to your CUDA installation, but if you plan on running the toolbox CPU-only (which isn't explicitly supported by this toolbox, but has been done by others in the past, such as [here](https://github.com/ubicomplab/rPPG-Toolbox/issues/176)) and don't care about using PhysMamba, you can probably ignore the error and use other parts of the toolbox.

**Comment by 3051485652** [comment]
> Do you have CUDA properly installed on your system? You can check by trying `nvcc --version`. If you don't have it installed, try installing CUDA first before trying the installation process again.
> 
> The issue appears to be specific to your CUDA installation, but if you plan on running the toolbox CPU-only (which isn't explicitly supported by this toolbox, but has been done by others in the past, such as [here](https://github.com/ubicomplab/rPPG-Toolbox/issues/176)) and don't care about using PhysMamba, you can probably ignore the error and use other parts of the toolbox.

If I don't need to use manba, can I ignore this error?

**Comment by yahskapar** [comment]
Maybe try using `pip` to install `tokenizers` manually, perhaps an earlier version of `tokenizers`. Not totally sure why you're running into that issue, but I would go through the usual steps to troubleshoot build issues from online searches (e.g., use `pip install --upgrade pip` to make sure you have the latest `pip`). You can also ignore the error, but maybe it's best you resolve this build issue since otherwise you'd have to comment out parts of this repo related to PhysMamba.

**Comment by 3051485652** [comment]
> Maybe try using `pip` to install `tokenizers` manually, perhaps an earlier version of `tokenizers`. Not totally sure why you're running into that issue, but I would go through the usual steps to troubleshoot build issues from online searches (e.g., use `pip install --upgrade pip` to make sure you have the latest `pip`). You can also ignore the error, but maybe it's best you resolve this build issue since otherwise you'd have to comment out parts of this repo related to PhysMamba.

This issue was caused by the compatibility between transformers and tokenizers. I resolved it by downgrading the transformers package.

**Comment by WONNNNNNN** [comment]
> hope this message finds you well. I am reaching out regarding the [Project Name] repository. While setting up the environment as instructed, I encountered an issue during the installation of [specific package or dependency causing the issue, e.g., causal-conv1d]. The error message I received is:
> 
> error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [13 lines of output] /tmp/pip-install-4nd9oerq/causal-conv1d_ab21852e1fef4709b3d9f6f0f45b2e49/setup.py:77: UserWarning: causal_conv1d was requested, but nvcc was not found. Are you sure your environment has nvcc available? If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc. warnings.warn( Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/tmp/pip-install-4nd9oerq/causal-conv1d_ab21852e1fef4709b3d9f6f0f45b2e49/setup.py", line 111, in if bare_metal_version >= Version("11.8"): NameError: name 'bare_metal_version' is not defined
> 
> ```
>   torch.__version__  = 2.1.2+cu121
>   
>   
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.
can you tell me how you solved this problem?
