### ISSUE TITLE
Some problems encountered when adding new datasets for training

### ISSUE THREAD

**Issue by zhusiyi601** [ubicomplab/rPPG-Toolbox#343]
Hope this message finds you well.I have successfully run the pure-pure-ubfc-tscan model using the rppg-toolbox, and I'm now trying to train the model on the DEAP dataset. I have already completed the necessary data loader and YAML configuration files, and the training process runs without any errors. However, after training for 30 epochs, I noticed that the loss does not decrease, and the model fails to converge.

Here is a loss plot from the training:
![image](https://github.com/user-attachments/assets/3de13266-5f17-4c8c-ae7b-208e8c8c3989)

I suspect that the issue might be related to data preprocessing. Below is an example of the preprocessed data after applying the diffnormalize method. As you can see, the data doesn't seem to be in a good condition.

![image](https://github.com/user-attachments/assets/29c8c256-51d4-4455-8c0a-c6ca83a248f8)

Could you kindly provide any advice on what might be causing this issue, and how I can improve the training process or preprocessing?

Thank you for your time and help.

**Comment by yahskapar** [comment]
I'm not too familiar with this particular dataset, and therefore can't really comment on using it, but I agree that difference frame doesn't look good. I generally recommend starting off with unsupervised methods, which don't use difference frames for that matter, with any new dataset. An example config can be found [here](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/configs/infer_configs/UBFC-rPPG_UNSUPERVISED.yaml).

It's possible that this particular dataset is difficult to use for rPPG with any of supervised methods in this toolbox, or perhaps requires preprocessing that isn't supported by this toolbox. Before even figuring that out, try the unsupervised methods and let us know what the results look like.

**Comment by zhusiyi601** [comment]
Thank you for your very timely advice. I will try using unsupervised methods in the next two days.

**Comment by zhusiyi601** [comment]
I have tried unsupervised methods, and OMIT and LGI have the best experimental results.The following figure is a scatterplot of OMIT.
![image](https://github.com/user-attachments/assets/b97f76f0-bc43-4b42-aa9b-d1f8c68f78f7)
 It should be noted that I only used a small part of the DEAP dataset for testing, but I think this can prove that the unsupervised method performs well on this dataset. Thank you very much for your suggestion, you can close this issue at any time.

**Comment by yahskapar** [comment]
Good to hear that you got better results with some of the unsupervised methods! It's worth not losing hope with the supervised methods - perhaps there's some modifications you can make to the default training configs or maybe you can try [weakly supervised training](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#green_book-weakly-supervised-training) to see if that would make a difference with your results.

I'll go ahead and close this issue for now, but feel free to follow-up with any new questions or concerns in a separate issue.

All the best,

Akshay
