### ISSUE TITLE
KeyError: 'Non-existent config key: DATA'

### ISSUE THREAD

**Issue by CrossguoAND** [ubicomplab/rPPG-Toolbox#61]
Hi, I got some troubles here. I try to train the TSCAN on PURE dataset, then I follow the steps. However, the ERROR mentioned:

_Traceback (most recent call last):
  File "main_neural_method.py", line 107, in <module>
    config = get_config(args)
  File "E:\code\rPPG-Toolbox\config.py", line 266, in get_config
    update_config(config, args)
  File "E:\code\rPPG-Toolbox\config.py", line 195, in update_config
    _update_config_from_file(config, args.config_file)
  File "E:\code\rPPG-Toolbox\config.py", line 190, in _update_config_from_file
    config.merge_from_file(cfg_file)
  File "D:\Anaconda3\envs\python38\lib\site-packages\yacs\config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "D:\Anaconda3\envs\python38\lib\site-packages\yacs\config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "D:\Anaconda3\envs\python38\lib\site-packages\yacs\config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: DATA'_

Could you tell me how to solve the problems? thanks very much.

**Comment by zyzzzz-123** [comment]
Hi! I think the situation might be that you use some old YAML file and it conflicts with the new code.
Actually, there are some updates to our toolbox;  you can pull the new main branch and they are sure to be correct.
Also, there are some new explanations of our YAML file and you refer to them if you have some questions about them.

Thank you for using our toolbox! Feel free to ask us if you still have problems!

**Comment by CrossguoAND** [comment]
Thanks for your help! Following what you said, I changed the newest branch, and the code could run successfully.
Besides, there are other problems. I am reading the **_Preprocessed_** part of the code, but I'm confused that there is no detail about it in the article of  _"Multi-Task Temporal Shift Attention Networks for On-Device Contactless Vitals Measurement"_... 
Could you please tell me where I can read the details of the **_Preprocessed_** part?

**Comment by xliucs** [comment]
Should be fixed.
