### ISSUE TITLE
The details of 'Preprocessed ' part

### ISSUE THREAD

**Issue by CrossguoAND** [ubicomplab/rPPG-Toolbox#69]
Hi! I am reading the Preprocessed part of the code, but I'm confused that there is no detail about it in the article "Multi-Task Temporal Shift Attention Networks for On-Device Contactless Vitals Measurement"...
Could you please tell me where I can read the details of the Preprocessed part?

**Comment by xliucs** [comment]
It is on the preprocessing steps in the toolbox. please refer to how we implement "normalized" and 'standardized' modules.
