### ISSUE TITLE
Questions about the training results

### ISSUE THREAD

**Issue by tangyuelm** [ubicomplab/rPPG-Toolbox#91]
Dear authors,

Thank you for this toolbox which really helps a lot. 

I followed the instructions to train the TSCAN on PURE dataset and tested on the UBFC dataset. The whole propress went well without error. However, I feel confused about the final testing results. I got
FFT MAE (FFT Label):2.7413504464285716
FFT RMSE (FFT Label):10.761795973358529
FFT MAPE (FFT Label):2.5531960308525843
FFT Pearson (FFT Label):0.8154277192381875
However, in the Deep Physiological Sensing Toolbox paper, the expected results are MAE 0.99 RMSE 2.41 MAPE 1.17 Pearson 0.99. I have no idea what causes such as difference. I only modified the data path, cache path, and do procress operation in the PURE_PURE_UBFC_TSCAN_BASIC.yaml file. All the parameters remain unchanged. 
The only difference I can find is the platform configuration. I ran the codes on our GPU server which has the following configuration. However, since the codes can run succefully, the different configuration should not matter. Would it be possible to provide any ideas about the accuracy gap? Thank you.

Best,
Yue

Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 8.2.2004 (Core)  (x86_64)
GCC version: (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Clang version: 9.0.1 (Red Hat 9.0.1-2.module_el8.2.0+309+0c7b6b03)
CMake version: version 3.11.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] advertorch==0.2.3
[pip3] numpy==1.19.5
[pip3] torch==1.7.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.0
[conda] advertorch                0.2.3                    pypi_0    pypi
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.0            py37h42c9631_2
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] torch                     1.7.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.8.0                    pypi_0    pypi

**Comment by xliucs** [comment]
@tangyuelm  Can you please start from an empy conda environment to install torch, cuda and all the libraries? We provide setup.sh script for you to set it up. I also just re-run the PURE_PURE_UBFC_TSCAN_BASIC.yaml, and got the following results. I think you might not get indentical results as I do but shuold be very close. 

FFT MAE (FFT Label):0.907258064516129
FFT RMSE (FFT Label):2.2984212927873133
FFT MAPE (FFT Label):1.0784116085425672
FFT Pearson (FFT Label):0.9938596854918589

**Comment by tangyuelm** [comment]
Dear @xliucs,

Thank you for the referenced results. I just cleaned up the installation space of our server and created a new environment with the same version of the libraries and got the following results for TSCAN:
FFT MAE (FFT Label):1.5066964285714286
FFT RMSE (FFT Label):3.430898693959687
FFT MAPE (FFT Label):1.6237812216940781
FFT Pearson (FFT Label):0.9818703212000844

I also tried other backbones with both my original environment (Pytorch 1.7.0) and the new environment (Pytorch 1.12.1) and got the following results.
DEEPPHYS:  
ori env
FFT MAE (FFT Label):1.4229910714285714
FFT RMSE (FFT Label):4.583011632421127
FFT MAPE (FFT Label):1.4905727890270397
FFT Pearson (FFT Label):0.9664653978944819
new env
FFT MAE (FFT Label):1.5904017857142858
FFT RMSE (FFT Label):4.67440274053785
FFT MAPE (FFT Label):1.6624682870094942
FFT Pearson (FFT Label):0.9662832091219697

PYHSNET: both of them reported the following error.
Train epoch 0:   0%|                                    | 0/186 [00:02<?, ?it/s]
Train epoch 0:   0%|                                    | 0/186 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 240, in <module>
    train_and_test(config, data_loader_dict)
  File "main.py", line 68, in train_and_test
    model_trainer.train(data_loader_dict)
  File "/ocean/projects/ccr200024p/tangyue/pro/rPPG-Toolbox-main/neural_methods/trainer/PhysnetTrainer.py", line 57, in train
    loss.backward()
  File "/jet/home/tangyue/.conda/envs/rppg-toolbox/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/jet/home/tangyue/.conda/envs/rppg-toolbox/lib/python3.8/site-packages/torch/autograd/__init__.py", line 166, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
  File "/jet/home/tangyue/.conda/envs/rppg-toolbox/lib/python3.8/site-packages/torch/autograd/__init__.py", line 67, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs

For signal methods, the results of the two methods are exactly the same.
Used Signal Method: ica
Peak MAE (Peak Label):6.192432677552833
PEAK RMSE (Peak Label):10.010687335977556
PEAK MAPE (Peak Label):5.882796756494925
PEAK Pearson  (Peak Label):0.8116257944418853
Used Signal Method: pos
Peak MAE (Peak Label):2.337011074240569
PEAK RMSE (Peak Label):4.113871715904776
PEAK MAPE (Peak Label):2.68451850404889
PEAK Pearson  (Peak Label):0.9735707939443582
Used Signal Method: chrome
Peak MAE (Peak Label):2.684982954529878
PEAK RMSE (Peak Label):4.5636880261247
PEAK MAPE (Peak Label):3.1334824933709906
PEAK Pearson  (Peak Label):0.9719370622352056
Used Signal Method: green
Peak MAE (Peak Label):10.06896217358238
PEAK RMSE (Peak Label):13.490165580910897
PEAK MAPE (Peak Label):10.566184505957388
PEAK Pearson  (Peak Label):0.6703146226553021
Used Signal Method: LGI
Peak MAE (Peak Label):5.129328729368617
PEAK RMSE (Peak Label):7.187124834911197
PEAK MAPE (Peak Label):5.414901990012414
PEAK Pearson  (Peak Label):0.8966509434117802
Used Signal Method: PBV
Peak MAE (Peak Label):10.065132734358164
PEAK RMSE (Peak Label):16.538449807288963
PEAK MAPE (Peak Label):11.416259049818049
PEAK Pearson  (Peak Label):0.5351572473451687
I am wondering whether these results are meaningful or not. If not, could you provide any hint on the possible reasons?

Besides, would it be necessary to add "from scipy.sparse import spdiags" in the /signal_methods/utils.py file? I met an error without adding it.

Best,
Yue

**Comment by xliucs** [comment]
Hi Sorry, the toolbox is still under rapid development. We are also confused why other folks can't reproduce the results. We found that different platforms (e.g., GPUs, CPUs) can yield different results, but we were able to reproduce identical results under the same hardware platform. P.s., did you use UBFC dataset (not UBFC-Phys)?

I think we will try to release the pretrained models soon and you can start from there.  For the signal processing method, we will try to looking into them.

**Comment by tangyuelm** [comment]
Dear Xliucs,

Thank you for the reply. I requested the UBFC dataset from https://sites.google.com/view/ybenezeth/ubfcrppg and used dataset2 with 42 subjects. Here is a screenshot of my data path. I will double-check if every video is downloaded correctly.

![image](https://user-images.githubusercontent.com/58452529/195156067-cef0f26f-7eac-42b3-bbe6-2183fe9e4bd2.png)

Best,
Yue

**Comment by tangyuelm** [comment]
Dear @xliucs,

I downloaded the UBFC dataset2 again but the results of the signal processing methods remain nearly unchanged. However, the inference results on the PURE dataset are quite similar to that reported in the paper. Here are my results on the PURE dataset. 
I am wondering if we use different pre-process and post-process parameters in the .yaml files. For example, I noticed that in your paper, the FFT is added, but some .yaml files use FFT while others use peak detection. I also tried signal processing with FFT on the UBFC but the results still have a difference from that in the paper. Please let me know if there are other reasons that I can try. Thank you.

Best,
Yue

Used Signal Method: ica
Peak MAE (Peak Label):5.678204638540967
PEAK RMSE (Peak Label):8.89137574781528
PEAK MAPE (Peak Label):6.841969596933812
PEAK Pearson  (Peak Label):0.8811212819785216
Used Signal Method: pos
Peak MAE (Peak Label):7.894317808996057
PEAK RMSE (Peak Label):11.084873524148394
PEAK MAPE (Peak Label):10.646831468992902
PEAK Pearson  (Peak Label):0.8932637389961042
Used Signal Method: chrome
Peak MAE (Peak Label):7.324036421733165
PEAK RMSE (Peak Label):10.381278832542732
PEAK MAPE (Peak Label):10.110064113079648
PEAK Pearson  (Peak Label):0.9003719680188776
Used Signal Method: green
Peak MAE (Peak Label):8.482186343364956
PEAK RMSE (Peak Label):11.595084337788286
PEAK MAPE (Peak Label):10.386059003709729
PEAK Pearson  (Peak Label):0.7802353949841767
Used Signal Method: LGI
Peak MAE (Peak Label):10.611006816616037
PEAK RMSE (Peak Label):15.762078068931755
PEAK MAPE (Peak Label):13.675594804617397
PEAK Pearson  (Peak Label):0.7245239465690155
Used Signal Method: PBV
Peak MAE (Peak Label):23.423810036003307
PEAK RMSE (Peak Label):30.413168069127664
PEAK MAPE (Peak Label):30.50302033771021
PEAK Pearson  (Peak Label):0.5240570949797602

**Comment by xliucs** [comment]
Hi sorry about the confusion. Please use FFT for all the inference and don't use peak detection. We have made a couple of changes in the toolbox after drafting the paper and not sure if that impacts the results of signal processing methods. Were able to get similar results on neural methods like TS-CAN?

**Comment by xliucs** [comment]
I will re-run the signal processing results by the end of this week let you know how it goes.

**Comment by tangyuelm** [comment]
Dear Xliucs,

Thank you for the help. I have rerun the TS-CAN after using the new environment and got the following results. Our server uses V-100 GPUs. Would you mind taking a look to see if the results make sense?

Best,
Yue
FFT MAE (FFT Label):1.5066964285714286
FFT RMSE (FFT Label):3.430898693959687
FFT MAPE (FFT Label):1.6237812216940781
FFT Pearson (FFT Label):0.9818703212000844

**Comment by tangyuelm** [comment]
And here are my results for signal methods.
Used Signal Method: ica
FFT MAE (FFT Label):18.655831473214285
FFT RMSE (FFT Label):27.955525552957976
FFT MAPE (FFT Label):18.119292528350574
FFT Pearson  (FFT Label):0.4628068992677564
Used Signal Method: pos
FFT MAE (FFT Label):4.1015625
FFT RMSE (FFT Label):7.6036941570633125
FFT MAPE (FFT Label):3.9445300812863806
FFT Pearson  (FFT Label):0.9226760046738337
Used Signal Method: chrome
FFT MAE (FFT Label):4.206194196428571
FFT RMSE (FFT Label):8.82560761605004
FFT MAPE (FFT Label):3.935475405780711
FFT Pearson  (FFT Label):0.8804517442968289
Used Signal Method: green
FFT MAE (FFT Label):23.583984375
FFT RMSE (FFT Label):34.7252723323003
FFT MAPE (FFT Label):22.058897108035637
FFT Pearson  (FFT Label):0.2542478334814739
Used Signal Method: LGI
FFT MAE (FFT Label):15.778459821428571
FFT RMSE (FFT Label):28.385212015503317
FFT MAPE (FFT Label):14.704179399230016
FFT Pearson  (FFT Label):0.3516596017472303
Used Signal Method: PBV
FFT MAE (FFT Label):18.205915178571427
FFT RMSE (FFT Label):29.60253150785561
FFT MAPE (FFT Label):17.04423798579935
FFT Pearson  (FFT Label):0.35914645537391726

**Comment by xliucs** [comment]
Thanks for sharing these results. It is very odd that you can't reproduce our neural methods' results. I think we will release pre-trained models then. I use 4 2080Ti with distribued training setting. If you only use 1 Tesla V100, you should make sure the NUM_OF_GPU to be 1. We use the batch size 4 and not sure what is your batch size. 

For the signal processing methods, we will go through the results and update the paper by EOD if necessary. 

We apologize again as the toolbox is under quick dev peace and some changes might cause discrepancies on the final results.

**Comment by wangningbin** [comment]
Hello, I want to ask whether you have used the Physnet model to train and test on UBFC and PURE datasets. I found that there is a big gap between the training and testing and that in the paper. I wonder if you have the same problem as me. Could you leave your email address if it is convenient

**Comment by xliucs** [comment]
@wangningbin  We have largely updated the toolbox in the month and there is possible gap between the paper and the master branch. I think the toolbox will become stable starting from next week and will re-run all the experiments and update the paper. Moreover, we will release all the pre-trianed models from the toolbox to ensure the reproducibility.

**Comment by tangyuelm** [comment]
Dear @xliucs,

Thank you for the reply. I used one GPU node and the NUM_OF_GPU is 1, while the batch size is indeed 4. I look forward to comparing my results to the newest benchmarks.

Dear @wangningbin,

I got an error training PhysNet on PURE and testing it on UBFC, so I have not tried this backbone with other datasets combinations yet. Would you like to share your results as well so that we can see if our results can match after I run it?

Best,
Yue

**Comment by xliucs** [comment]
@tangyuelm Hi I might know the reason now. UBFC people replaced a few subjects recently. The UBFC data I used is a old version. Will release pre-trianed models on the new UBFC dataset and update the results soon. Also, we also acknowledge that training with different GPU/platform might cause slight discrenpency on the final performance thus please use our-pretrained models as the gold-standard reference. You should be able to replicate the results with our pre-trained models.

**Comment by harshithshankar13** [comment]
Hello, @xliucs thanks for this fabulous work. Results from the pretrained model updated 2 years ago are not up to the mark for my use case. When can we expect new pretrained models?  -Thanks.

**Comment by tangyuelm** [comment]
Dear @xliucs, 

I see. Thank you for the explanation. Please let me know when the newest pre-trained models are released.

Best,
Yue

**Comment by xliucs** [comment]
@harshithshankar13  Yes, we will release new models soon.

**Comment by xliucs** [comment]
Hi Sorry, we have been doing large reformating and update to the toolbox. You can use the pre-trianed models now. Pleasse refer to the latest readme.
